4 front task onboarding publish
Meetie-One/Meetie-front pull request #10
Opened 2024-08-11 03:03 UTC by ejinn1

- https://github.com/Meetie-One/Meetie-front/issues/4

## 💡 변경사항 & 이슈
온보딩과정 퍼블리싱
- 홈 (스플래쉬 화면)
- 로그인
- 워크쓰루
- 온보딩
- 회원가입 완료

<br>

## ✍️ 관련 설명
온보딩 과정 화면들을 퍼블리싱 했습니다.
아이콘이나 사진 등은 넣지 않았습니다.
버튼 부분은 공통 컴포넌트가 생기면 대체될 예정입니다.

<br>

## ⭐️ Review point
디자인에 문제가 있거나 리펙토링 가능한 부분 말씀해주시면 감사하겠슴니다.

<br>

## 📷 Demo
### 홈 (스플래쉬 화면) `/home`
<img width="375" alt="image" src="https://github.com/user-attachments/assets/d30401d7-fc9d-45d0-9bde-c4785b0540e8">

###  로그인 `/login`
<img width="375" alt="image" src="https://github.com/user-attachments/assets/c10f78c1-ed9c-4ded-9fe3-6a21a05640c0">

### 워크쓰루 `/walkThrough`
<img width="373" alt="image" src="https://github.com/user-attachments/assets/e6f26976-fa05-4944-a5bd-e6e92a840705">

###  온보딩 `/onBoarding/[step]`
- `/onBoarding/1`
<img width="377" alt="image" src="https://github.com/user-attachments/assets/ad4a4890-653c-4028-a50e-01d32a755713">

- `/onBoarding/2`
<img width="374" alt="image" src="https://github.com/user-attachments/assets/89892969-25f4-4118-9b31-a467d8f03c88">

- `/onBoarding/3`
<img width="375" alt="image" src="https://github.com/user-attachments/assets/2b4f8fc9-c182-4081-96dd-25de901e30da">

- `/onBoarding/4`
<img width="375" alt="image" src="https://github.com/user-attachments/assets/44da1e0a-f9da-479f-8902-2a5368fd9495">

### 회원가입 완료 `/onBoarding/conplete`
<img width="371" alt="image" src="https://github.com/user-attachments/assets/689f85f2-8aeb-44fc-bf30-52bac7a1e467">

<br>

2024-08-12 06:21 UTC, sikkzz requested changes

2024-08-12 06:21 UTC, sikkzz commented on apps/meetie-service/src/app/home/page.tsx
이거 home 디렉토리 만들지 말고 그냥 app/page.tsx로 옮기는게 나을 거 같아요

2024-08-12 06:21 UTC, sikkzz commented on apps/meetie-service/src/app/home/page.tsx
> +      <Link href={"/login"}>
href="/login"

중괄호 없어도 작동해요

2024-08-12 06:21 UTC, sikkzz commented on apps/meetie-service/src/app/home/page.tsx
> +            <div className="mb-[70px] w-[212px] h-[240px] bg-primary-400">로켓 이미지</div>
todo 이미지 변경 예정 주석같은거 달아놓으면 좋을 거 같아요

2024-08-12 06:21 UTC, sikkzz commented on apps/meetie-service/src/app/home/page.tsx
> +              <button className="w-[46px] h-[46px] rounded-full bg-black text-white">...</button>
여기도 todo icon 변경 예정 주석

적어놓으면 리뷰하는 입장에서도 인지하기 쉽고 나중에 코드 봤을 때 누락시키지 않을 수 있는 장점이 있어요

2024-08-12 06:21 UTC, sikkzz commented on apps/meetie-service/src/app/home/page.tsx
> +          <div>비밀번호찾기</div>
보통 저런 요소는 ::after나 ::before 가상 요소를 많이 사용해요 한번 서칭해보고 적용시켜보세요

2024-08-12 06:21 UTC, sikkzz commented on apps/meetie-service/src/app/home/page.tsx
> +        </footer>
footer tag가 어울리는 요소는 아닌 거 같아요

그냥 div로 사용하고 추가적으로 login 페이지에서도 동일하게 사용할 수 있어보이는데 컴포넌트로 빼면 그대로 사용할 수 있겠네요

2024-08-12 06:21 UTC, sikkzz commented on apps/meetie-service/src/app/login/page.tsx
> +      </footer>
home에서 컴포넌트 빼서 사용

2024-08-12 06:21 UTC, sikkzz commented on apps/meetie-service/src/app/login/page.tsx
> +          </div>
여기 divider들도 가상 요소를 쓰면 더 좋긴 하겠네요

2024-08-12 06:21 UTC, sikkzz commented on apps/meetie-service/src/app/login/page.tsx
> +            />
속성이 다른게 없을 거 같은데 컴포넌트로 사용하거나 className 변수화 해서 사용해도 될 거 같아요 password input에도 동일하게 placeholder 텍스트 color가 필요할 거 같은데 누락된거 보면 이런 누락을 방지할 수도 있겠네요

2024-08-12 06:21 UTC, sikkzz commented on apps/meetie-service/src/app/login/page.tsx
> +            />
placeholder *로 걸어줘야하겠네요

2024-08-12 06:21 UTC, sikkzz commented on apps/meetie-service/src/app/login/page.tsx
> +            <h1 className="text-start text-semibold-24 ">
text-start 없어도 동일하지 않나요?

2024-08-12 06:21 UTC, sikkzz commented on apps/meetie-service/src/app/login/page.tsx
> +            </h1>
이렇게 쓰는거 보다 h1 태그 두개를 쓰는게 더 보편적인거 같은데 span 두개로 내부에 나눈 이유가 있을까용

2024-08-12 06:21 UTC, sikkzz commented on apps/meetie-service/src/app/login/page.tsx
> +            </label>
체크박스 아이콘이 제대로 안뜨는거 같네요 이후 추가 예정이면 주석 처리 하나 부탁드려요~

2024-08-12 06:21 UTC, sikkzz commented on apps/meetie-service/src/app/login/page.tsx
> +            <Link href={"/walkThrough"}>
중괄호 제거

2024-08-12 06:21 UTC, sikkzz commented on apps/meetie-service/src/app/login/page.tsx
> +          </div>
주석 아이콘 todo

2024-08-12 06:21 UTC, sikkzz commented on apps/meetie-service/src/app/onBoarding/[step]/page.tsx
> +    navigate.push(`/onBoarding/${step - 1}`);
step === 1 || navigate.push(`/onBoarding/${step - 1}`);

이러면 훨씬 축약되긴 합니다. 인라인으로 쓸때는 더욱 효율을 볼 수 있겠지만 함수상에서도 코드 양은 이득일 거 같네요

2024-08-12 06:21 UTC, sikkzz commented on apps/meetie-service/src/app/onBoarding/[step]/page.tsx
> +    navigate.push(`/onBoarding/${step + 1}`);
여기도 상단이랑 동일

2024-08-12 06:21 UTC, sikkzz commented on apps/meetie-service/src/app/onBoarding/[step]/page.tsx
> +  const step = Number(pathName.split("/").pop());
useParams 쓰고 param.step으로 뽑는게 더 편하지 않을까요?

2024-08-12 06:21 UTC, sikkzz commented on apps/meetie-service/src/app/onBoarding/[step]/page.tsx
> +            <span className="block">{step && QUESTION[step - 1].TITLE.FIRST}</span>
아래도 다 해당되는 내용인데 step &&가 들어간 이유가 있나요?

2024-08-12 06:21 UTC, sikkzz commented on apps/meetie-service/src/app/onBoarding/[step]/page.tsx
> +        <button className="uppercase ">skip</button>
뒤에 공백 지워야겠네요. 추가적으로 uppercase 쓸 필요 없이 SKIP으로 명시하는게 낫지 않을까요?

2024-08-12 06:21 UTC, sikkzz commented on apps/meetie-service/src/app/onBoarding/[step]/page.tsx
onboarding/1
onboarding/2

저는 이렇게 number로 쓰는거 보다 상수화된 네이밍을 뽑아서 쓰는게 더 좋다고 생각해요.

예를 들어 onboarding/job onboarding/select-job, onboadring/style 등 네이밍이 어렵긴 하겠지만 url에 저런 기본적인 number가 들어가면 디버깅 에러나 원하는대로 작동하지 않을 여지가 남게 됩니다.

그리고 onboarding?step=job 이런식으로 저는 searchParams 많이 사용했던 거 같아요 한번 고려해보시기 바랍니다

2024-08-12 06:21 UTC, sikkzz commented on apps/meetie-service/src/app/walkThrough/page.tsx
> +  const [number, setNumber] = useState(0);
그냥 number라 네이밍하면 무슨 number인지 한눈에 파악하기 어려울 거 같네요

2024-08-12 06:21 UTC, sikkzz commented on apps/meetie-service/src/app/walkThrough/page.tsx
> +          ))}
key값을 안넣어줘서 콘솔에서 에러가 뜨네요

2024-08-12 06:21 UTC, sikkzz commented on apps/meetie-service/src/app/walkThrough/page.tsx
> +          ></button>
```jsx
          {Array.from({ length: 3 }, (_, index) => (
            <button
              onClick={() => handleClickNumber(index)}
              className={`w-[10px] h-[10px] rounded-full ${number === index ? "bg-primary-400" : "bg-gray-100"}`}
              key={`button${index}`}
            />
          ))}
```

코드 간소화 시켜드렸어요 이해 안가면 질문 주세요

2024-08-12 06:21 UTC, sikkzz commented on apps/meetie-service/src/components/onBoardings/OnBoardingFirstStep.tsx
> +type Jobs = "designer" | "developer" | "planner";
컨벤션 맞춘대로 interface랑 네이밍 수정 부탁드려요

2024-08-12 06:21 UTC, sikkzz commented on apps/meetie-service/src/components/onBoardings/OnBoardingFirstStep.tsx
> +        </button>
여기도 map 사용해서 축약 가능할 거 같아요 이후에 아이콘 props도 하나 받을거 고려해야겠네요

해보고 어려우면 말씀해주세요

2024-08-12 06:21 UTC, sikkzz commented on apps/meetie-service/src/components/onBoardings/OnBoardingFirstStep.tsx
> +    setClickedJob(value);
변수 하나 새로 할당할 필요 없이 바로 넣어도 되지 않을까요? 제가 모르는 이유가 있다면 말씀해주세요~

setClickedJob(e.currentTarget.value as Jobs);

2024-08-12 06:21 UTC, sikkzz commented on apps/meetie-service/src/components/onBoardings/OnBoardingFourthStep.tsx
> +    }
clickedPeriod !== newPeriod ? setClickedPeriod(newPeriod) : setClickedPeriod("");

이럴땐 삼항 연산자 사용시 훨씬 깔끔합니다~

2024-08-12 06:21 UTC, sikkzz commented on apps/meetie-service/src/components/onBoardings/OnBoardingFourthStep.tsx
> +            ></div>
```jsx
<div className={`w-[20px] h-[20px] rounded-full ${clickedPeriod.includes(period) ? "bg-primary-500" : "bg-gray-100"}`} />
```

닫는 태그로만 해결이 가능해요

2024-08-12 06:21 UTC, sikkzz commented on apps/meetie-service/src/components/onBoardings/OnBoardingSecondStep.tsx
위에서 리뷰한 내용들중 겹치는게 있다면 확인하고 수정 부탁드려요~

2024-08-12 07:40 UTC, ejinn1 commented on apps/meetie-service/src/app/login/page.tsx
> +            </h1>
아녀 없어용

2024-08-12 07:52 UTC, ejinn1 commented on apps/meetie-service/src/app/onBoarding/[step]/page.tsx
> +  const step = Number(pathName.split("/").pop());
생각 못했습니다..

2024-08-12 08:32 UTC, ejinn1 commented on apps/meetie-service/src/app/onBoarding/[step]/page.tsx
> +            <span className="block">{step && QUESTION[step - 1].TITLE.FIRST}</span>
타입이 undefined 가능성이 있다고 했는데 로직 수정하면서 사라져서 수정했슴니다

2024-08-12 08:34 UTC, ejinn1 commented on apps/meetie-service/src/app/onBoarding/[step]/page.tsx
넵 위에 방식대로 로직 수정했습니다

2024-08-13 01:03 UTC, detourguru commented on apps/meetie-service/src/app/login/page.tsx
> +          {/* todo icon 변경 예정 */}
extension 중에 todo highlighter라고  있는데 주석으로 많이써놨을때 유용해요 추천드립니당

2024-08-13 01:04 UTC, detourguru commented on apps/meetie-service/src/app/login/page.tsx
> +        <p className="text-gray-200 mb-[24px] text-medium-12 before:w-[153px] before:bg-gray-200 before:h-[1px] before:inline-block before:mb-[3px] before:mr-[10px] after:ml-[10px] after:w-[153px] af
4의 배수로 떨어지는 것들은 커스텀으로 픽셀을 지정해주는 것보단 지원하는 클래스를 사용하는게 깔끔할 것 같습니다!

2024-08-13 01:18 UTC, ejinn1 commented on apps/meetie-service/src/app/login/page.tsx
> +          {/* todo icon 변경 예정 */}
넵 한번 확인해보겠습니당

2024-08-14 01:18 UTC, ejinn1 commented on apps/meetie-service/src/components/onBoardings/OnBoardingFirstStep.tsx
> +    setClickedJob(value);
콜솔로 값이 맞는 지 찍어보다가 저렇게 한거 같아요 수정하겠습니당

2024-08-14 01:28 UTC, ejinn1 commented on apps/meetie-service/src/components/onBoardings/OnBoardingFirstStep.tsx
> +        </button>
컴포넌트로 따로 빼는걸 고려해서 props로 받는걸 고려하는 걸까요 
```js
const JOBS = ["designer", "developer", "planner"];
// ...

{JOBS.map((job, index) => (
      //...
      <Image src={`/svg/ic-jobs-${job}.svg`}
        alt="icon"
        width={18}
        height={20}
      />
```
위 방식처럼 아이콘 적용시키는 방법으로 생각했습니다.

2024-08-14 03:15 UTC, ejinn1 commented on apps/meetie-service/src/components/onBoardings/OnBoardingFourthStep.tsx
> +    }
저 방식은 생각 못해봤어요 수정하겠습니당

2024-08-14 03:38 UTC, ejinn1 commented on apps/meetie-service/src/app/login/page.tsx
> +        <p className="text-gray-200 mb-[24px] text-medium-12 before:w-[153px] before:bg-gray-200 before:h-[1px] before:inline-block before:mb-[3px] before:mr-[10px] after:ml-[10px] after:w-[153px] af
넵 수정했습니다!

2024-08-15 04:24 UTC, sikkzz commented on apps/meetie-service/src/components/onBoardings/OnBoardingFirstStep.tsx
> +        </button>
해당 방식으로 해도 괜찮을 거 같네요~

2024-08-15 04:35 UTC, sikkzz approved these changes

2024-08-16 01:10 UTC, jisong3377 approved these changes

2024-08-19 03:33 UTC, soyoung125 approved these changes

2024-08-19 04:24 UTC, detourguru approved these changes

2024-08-19 05:20 UTC, merged