92 front task create community post page
Meetie-One/Meetie-front pull request #100
Opened 2024-09-09 05:16 UTC by soyoung125

- [GITHUB ISSUE LINK]()

## 💡 변경사항 & 이슈
커뮤니티 게시글 read 페이지 구현
게시글 수정, 삭제 구현
게시글 댓글 작성, 삭제 구현
<br>

## ✍️ 관련 설명
커뮤니티 페이지에서 게시글 카드를 선택 시 해당 게시글 페이지로 이동하면서 viewCount 증가

본인이 작성한 게시글에 대해 수정/삭제 권한 부여

게시글에 댓글 작성/삭제 구현

게시글에 대한 이모지 반응은 미구현상태입니다. 로그아웃 구현 후 다시 개발 진행할 예정입니다.
<br>

## ⭐️ Review point
게시글 읽기/수정/삭제, 게시글 댓글 작성/삭제  테스트해보시고 문제가 발견된다면 말씀해주세요.
<br>

## 📷 Demo
`페이지 접근 및 댓글 작성/삭제`
https://github.com/user-attachments/assets/25b79406-0d88-4263-be5a-76f836501f83

`게시글 수정/삭제`
https://github.com/user-attachments/assets/7043d36a-f0aa-43e7-919f-5871ae04cee5

<br>

2024-09-09 09:25 UTC, sikkzz requested changes
<img width="449" alt="스크린샷 2024-09-09 오후 6 25 19" src="https://github.com/user-attachments/assets/36ac2910-14fd-497a-b172-c0d2e8e3de81">

하단에 여백이 좀 있으면 좋을 거 같아요. 수치는 넣어보고 적당히 부탁드려요!

2024-09-09 09:25 UTC, sikkzz commented on public/svg/ic-community-add-emoji.svg
<img width="908" alt="스크린샷 2024-09-09 오후 6 12 22" src="https://github.com/user-attachments/assets/92cce4d3-b6a6-4955-8597-ae30473f7c97">

이미지 업로더 key 에러 납니다 확인 부탁드려용 여기서 수정된게 아니라 그냥 여기 달아요

2024-09-09 09:25 UTC, sikkzz commented on src/components/Community/ReadPost/PostDetail/PostFooter/PostFooter.tsx
> +            onClick={() => handleSubmit()}
onClick={handleSumbit} 했을 때 문제 없을 거 같아요

2024-09-09 09:25 UTC, sikkzz commented on src/hooks/api/community-comments/useCommentsQuery.ts
> +  },
호출 함수 따로 작성하기로 한거 수정 부탁드려요

2024-09-09 10:04 UTC, soyoung125 commented
![image](https://github.com/user-attachments/assets/69e11381-e595-443e-b0ce-2a299851f8b7)
하단 이정도면 될까요?

2024-09-10 01:30 UTC, sikkzz commented
> ![image](https://private-user-images.githubusercontent.com/77377583/365606588-69e11381-e595-443e-b0ce-2a299851f8b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MzIwMTIsIm5iZiI6MTcyNTkzMTcxMiwicGF0aCI6Ii83NzM3NzU4My8zNjU2MDY1ODgtNjllMTEzODEtZTU5NS00NDNlLWIwY2UtMmEyOTk4NTFmOGI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDAxMjgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1NjZmYmVmOGM0YmZiYWMzYTg4YjUyNjU1NTEyYmU5OTI4MmEyNzc2Zjg0YzYxNzg5ODJjOTEyYmI3NzAzZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vN5mebqPcth1KgGSyS3JLp-JNAYN613v5Y2icoM2CqU) 하단 이정도면 될까요?

지금 수치로 85px 같은데 120px해주실래요?

2024-09-10 01:50 UTC, soyoung125 commented
수정했습니다.

2024-09-10 03:26 UTC, sikkzz approved these changes

2024-09-10 05:45 UTC, ejinn1 approved these changes

2024-09-10 09:10 UTC, jisong3377 commented
커뮤니티에서 게시글 등록/수정/삭제 댓글등록/삭제 기능 정상 테스트했습니다~

2024-09-10 09:10 UTC, jisong3377 approved these changes

2024-09-11 05:28 UTC, merged