99 front task feature onboarding data edit
Meetie-One/Meetie-front pull request #106
Opened 2024-09-09 10:00 UTC by ejinn1

- https://github.com/Meetie-One/Meetie-front/issues/99

## 💡 변경사항 & 이슈
onboarding 테이블 userinfo에 병합, position, styles 수정 구현
<br>

## ✍️ 관련 설명
onboarding query관련 부분을 userinfo로 합쳤습니다.

`user/[id]/edit` 페이지에서 직무, 스타일을 변경할 수 있도록 했습니다.

`/api/user-info/[id]`로 요청보내고 있는 부분이 많은 곳에 겹쳐있어서 다음 브랜치에서 수정하거나 해야할거같습니다.
<br>

## ⭐️ Review point
제가 테스트 했을 때 오류났던건 다 고쳤는데 온보딩부터 진행했을 때 에러 있으면 말씀해 주세요
<br>

## 📷 Demo

https://github.com/user-attachments/assets/25b29d69-ccd3-42dc-8ef2-2e6e087a193f

<br>

2024-09-10 04:02 UTC, sikkzz requested changes

2024-09-10 04:02 UTC, sikkzz commented on src/components/OnBoarding/Complete/Complete.tsx
<img width="226" alt="스크린샷 2024-09-10 오후 12 44 00" src="https://github.com/user-attachments/assets/6d638ad9-ffcc-4e72-996e-e32898ddfea0">

여기 텍스트 범위 처리 해야할 거 같네요

2024-09-10 15:33 UTC, soyoung125 approved these changes

2024-09-10 16:05 UTC, soyoung125 approved these changes

2024-09-10 16:05 UTC, soyoung125 commented on src/app/api/user-info/route.ts
> +      return NextResponse.json({ message: error.message, status: 400 });
```
return NextResponse.json({ message: error.message }, { status: 400 });
```
이렇게 해야 의도대로 status가 넘어갑니다!

2024-09-11 03:03 UTC, ejinn1 commented on src/app/api/user-info/route.ts
> +      return NextResponse.json({ message: error.message, status: 400 });
이건 이후에 전체적으로 수정해야할거같슴니다! 다른 부분도 다 이렇게 되어있어서

2024-09-11 03:03 UTC, ejinn1 commented on src/components/OnBoarding/Complete/Complete.tsx
일단은 11자리로 잘라놨어요

2024-09-11 05:32 UTC, merged