165 front task test login part e2e test
Meetie-One/Meetie-front pull request #167
Opened 2024-10-15 04:28 UTC by ejinn1

- https://github.com/Meetie-One/Meetie-front/issues/165

## 💡 변경사항 & 이슈
전역 로그인 설정, 로그인/회원가입 테스트 코드 작성
<br>

## ✍️ 관련 설명
### 전역 로그인 설정
global-setup.ts로 전역으로 로그인을 진행했습니다.
`email: testing@test.com`
`password: test1234@`

`playwright/store/auth.json` 에 데이터 저장되도록 하였습니다.

### 로그인 테스트
1. 온보딩 미완료 유저가 로그인 했을 때 `/walk-through` 페이지로 이동하는지 테스트
2. 온보딩 완료 유저가 로그인 했을 때 `/study-room/list` 페이지로 이동하는지 테스트
3. 회원가입을 하지 않은 유저가 로그인 했을 때 `존재하지 않는 사용자입니다` 토스트 메시지 확인 테스트
4. 회원가입 되어있는 유저가 비밀번호를 틀렸을 때 `비밀번호가 잘못되었습니다` 토스트 메시지 확인 테스트

### 회원가입 테스트
1. 로그인 페이지에서 `회원가입하기` 버튼 눌렀을 때 회원가입 페이지로 이동하는지 테스트
2. 올바른 입력값으로 회원가입 되는 지 테스트
3. 잘못된 이메일 입력 시 토스트 메시지 확인 테스트
4. 잘못된 비밀번호 입력 시 토스트 메시지 확인 테스트
5. 잘못된 비밀번호 확인 입력 시 토스트 메시지 확인 테스트
6. 이메일 중복 시 토스트 메시지 확인 테스트

<br>

## ⭐️ Review point
전역 로그인에서 문제가 있거나 테스트 코드에서 문제가 있으면 말해주세여
<br>

## 📷 Demo
<img width="995" alt="image" src="https://github.com/user-attachments/assets/1e2905e1-6878-47e9-8fd7-3daf50f25789">

<img width="977" alt="image" src="https://github.com/user-attachments/assets/9a4ed827-2429-4496-9624-b2deeb80d430">

<br>

2024-10-15 10:15 UTC, sikkzz requested changes

2024-10-15 10:15 UTC, sikkzz commented on global-setup.ts
꼭 루트에 있어야 하는게 아니면 e2e 디렉토리로 옮기는게 좋을 거 같아요

2024-10-15 10:15 UTC, sikkzz commented on playwright.config.ts
> +  globalSetup: require.resolve("./global-setup.ts"),
옮기게 되면 여기도 수정하고 정상적으로 돌아가는지 테스트 부탁드려요

2024-10-15 10:15 UTC, sikkzz commented on src/e2e/login.spec.ts
<img width="1724" alt="스크린샷 2024-10-15 오후 7 07 28" src="https://github.com/user-attachments/assets/dbcc7d88-381b-4882-9bf6-fbe3dc1eda76">

e2e:ui로 테스트시 저만 이메일 검사 관련에서 실패하는걸까요?

2024-10-15 10:15 UTC, sikkzz commented on src/e2e/login.spec.ts
몇번 돌려보니까 아마 토스트 메시지 뜨는 작업에서 지연 시간이 있어서 실패하는 경우가 있고 성공하는 경우가 있는거 같네요. 개선할 수 있으면 개선하고 아니면 그냥 넘어가도 될 거 같아요

2024-10-15 10:15 UTC, sikkzz commented on src/e2e/login.spec.ts
> +test.use({ storageState: { cookies: [], origins: [] } });
global-setup을 통해 자동 로그인을 시켜주는건데 여기선 비로그인 상태가 필요하기 때문에 storage를 이렇게 초기화 시켜주는 코드가 제대로 이해한게 맞을까요?

2024-10-16 02:24 UTC, soyoung125 commented on src/e2e/login.spec.ts
> +    await expect(page.getByText(ERROR_MESSAGE.LOGIN("not exist user error"))).toBeVisible();
toast 검사할 때  `e2e:ui`로 테스트하면 오류가 납니다.
실행될 때 strict mode 여서 2개의 요소가 감지된다고 하더라고요.
그래서 저는 
```
      const toast = (await page.getByText("이미지는 최대 5개까지 가능합니다.").all())[0];
      await expect(toast).toBeVisible();
```
이런 식으로 하나의 요소만 가져오도록 코드를 작성했는데 이 방법 외에 다른 방법이 있다면 말씀해주세요!

2024-10-16 06:04 UTC, ejinn1 commented on src/e2e/login.spec.ts
> +test.use({ storageState: { cookies: [], origins: [] } });
네 맞아요

2024-10-16 06:05 UTC, ejinn1 commented on src/e2e/login.spec.ts
> +    await expect(page.getByText(ERROR_MESSAGE.LOGIN("not exist user error"))).toBeVisible();
저 방법으로 수정해보겠습니당

2024-10-16 06:07 UTC, ejinn1 commented on global-setup.ts
넵

2024-10-16 06:51 UTC, ejinn1 commented on src/e2e/login.spec.ts
일단은 넘어가겠습니다

2024-10-16 07:42 UTC, sikkzz commented on src/e2e/login.spec.ts
> +    await expect(page.getByText(ERROR_MESSAGE.LOGIN("not exist user error"))).toBeVisible();
<img width="912" alt="스크린샷 2024-10-16 오후 4 40 56" src="https://github.com/user-attachments/assets/77aaca4b-f631-401a-b41a-e1e62e5fa019">

수정 이후에는 딴 에러가 뜨는데 저만 뜨나요?

2024-10-16 10:15 UTC, ejinn1 commented on src/e2e/login.spec.ts
> +    await expect(page.getByText(ERROR_MESSAGE.LOGIN("not exist user error"))).toBeVisible();
이게 될떄가 있고 안될때가 있는데 잘 모르겠네요

2024-10-17 05:19 UTC, sikkzz approved these changes

2024-10-17 07:06 UTC, soyoung125 approved these changes

2024-10-18 02:27 UTC, merged