5 front task create a feature
Meetie-One/Meetie-front pull request #19
Opened 2024-08-13 18:15 UTC by jisong3377

- [GITHUB ISSUE LINK]()

## 💡 변경사항 & 이슈
- 캘린더 페이지 
- 과제 인증 페이지 
- 과제 인증 완료 페이지 
- 과제 인증 상세페이지
<br>

## ✍️ 관련 설명
- SVG ICON 분리
- 헤더 및 버튼 공동 컴포넌트 적용 안 된 상태 
<br>

## ⭐️ Review point
캘린더 페이지에 일주일 간의 달력을 보여주는 부분이 있는데
구현 관련해서 코멘트 부탁드립니다.
<br>

## 📷 Demo
<img width="254" alt="스크린샷 2024-08-14 오전 3 07 07" src="https://github.com/user-attachments/assets/f57bea4b-f6e9-431e-81ac-f3d342acafdb">

<img width="322" alt="스크린샷 2024-08-14 오전 3 04 25" src="https://github.com/user-attachments/assets/f11313ea-5a12-4115-ba7e-239ab513ed02">

<img width="396" alt="스크린샷 2024-08-14 오전 3 03 32" src="https://github.com/user-attachments/assets/018833f3-a9a2-4913-80c6-f08da6aea55c">

<img width="269" alt="스크린샷 2024-08-14 오전 3 05 49" src="https://github.com/user-attachments/assets/b1d3497b-c7df-4ebc-84e2-adda141a7590">

<br>

2024-08-14 01:11 UTC, ejinn1 commented on apps/meetie-service/src/app/calendar/page.tsx
>                <span className="text-medium-12 text-[--primary-500]">월</span>
text-primary-500으로 해도 적용 될거에요

2024-08-14 01:11 UTC, ejinn1 commented on apps/meetie-service/src/app/calendar/page.tsx
> +          <div className="flex items-center mt-6 mb-3 px-4 py-3 bg-[#F5F5F5] border border-[--primary-500] rounded-lg">
여기도 border-primary-500으로 해도 적용 되요

2024-08-14 01:11 UTC, ejinn1 commented on apps/meetie-service/src/app/calendar/page.tsx
> +            <div className="absolute top-4 right-4 flex items-center justify-center w-[50px] h-[50px] bg-white border-[5px] border-[--primary-500] rounded-full">
여기도 border-primary-500으로 해도 됩니당 다른 부분에도 수정하면 될거같습니다

2024-08-14 01:35 UTC, detourguru commented on apps/meetie-service/src/app/calendar/page.tsx
> +              <p className="px-[13px] py-[8px] bg-[#F4F4F4] border border-[--primary-500] rounded-full">
반복적으로 사용되는 컬러라면 별도로 테마로 등록해서 사용하시는건 어떨까요?

2024-08-14 01:41 UTC, detourguru commented on apps/meetie-service/src/app/confirm/page.tsx
> +            <span className="text-[20px] mr-3">🥸</span>
4의 배수로 떨어지는 숫자라면 임의 입력 말고 지원하는 클래스로 사용하면 될 것 같아요!

2024-08-14 09:45 UTC, sikkzz requested changes
전체적으로 컴포넌트 분리가 필요합니다.

이게 퍼블리싱 단계인데도 UI 코드들로 코드가 많은데 나중에 기능 로직이랑 api등이 들어가면 코드가 기하급수적으로 늘어납니다.

각 컴포넌트별로 분리를 해야 해당 컴포넌트에 보여지는 UI, 기능 로직들만 분리해서 확인할 수 있어요

2024-08-14 09:45 UTC, sikkzz commented on apps/meetie-service/public/img/userImg.png
img 컨벤션 양식 맞춰주세요

2024-08-14 09:45 UTC, sikkzz commented on apps/meetie-service/src/app/confirm/page.tsx
> +import React from "react";
지워도 문제 없습니다

2024-08-14 09:45 UTC, sikkzz commented on apps/meetie-service/src/app/confirm/page.tsx
> +import userImg from "/public/img/userImg.png";
Pascal case 적용 부탁드려요

2024-08-14 09:45 UTC, sikkzz commented on apps/meetie-service/src/app/confirm/page.tsx
> +const Confirm = () => {
page는 export default function 형식 사용하기로 했던거 같아요

2024-08-14 09:45 UTC, sikkzz commented on apps/meetie-service/src/app/confirm/page.tsx
> +      <div id="modal" className="hidden w-full h-screen" style={{ overflow: "hidden" }}>
style={{ overflow: "hidden" }} 삭제 부탁드려요

2024-08-14 09:45 UTC, sikkzz commented on apps/meetie-service/src/app/confirm/page.tsx
> +      </div>
react에서는 modal 구현시 react-portal을 주로 이용했다면, next에서는 Parallel-Routes와 Intercepting-Route를 사용해서 모달을 주로 구현합니다.

코드 및 로직 분리에 장점이 있으며 새로 고침시 모달 유지, state 관리 불필요 등의 장점이 있습니다. 서칭해보시고 리팩토링 권유드려요

2024-08-14 09:45 UTC, sikkzz commented on apps/meetie-service/src/app/confirm/page.tsx
> +            </div>
반복 코드인걸 감안하면 간소화가 가능해 보이네요

2024-08-14 09:45 UTC, sikkzz commented on apps/meetie-service/src/app/confirm/page.tsx
> +          <div className="w-9 h-[5px] bg-[#BFBFC1] rounded-full mx-auto mb-3"></div>
이건 모바일 디바이스 기준에서 보이는 디자인 예시라 구현은 필요 없어 보입니다. 삭제하면 될 거 같아요

2024-08-14 09:45 UTC, sikkzz commented on apps/meetie-service/src/app/confirm/page.tsx
> +        >
왜 인라인 스타일인걸까요?

2024-08-14 09:45 UTC, sikkzz commented on apps/meetie-service/src/app/confirm/page.tsx
> +        >
스크롤바도 없는게 자연스러울 거 같네요

2024-08-14 09:45 UTC, sikkzz commented on apps/meetie-service/src/app/confirm/page.tsx
> +            style={{ resize: "none" }}
인라인 제거

2024-08-14 09:45 UTC, sikkzz commented on apps/meetie-service/src/app/confirm/page.tsx
> +          <h3 className="inline text-medium-18 mr-3">14일차 과제</h3>
mr-3 제거하고 gap으로 처리 가능합니다

2024-08-14 09:45 UTC, sikkzz commented on apps/meetie-service/src/app/confirm/page.tsx
> +          <span className="inline px-[6px] py-[3px] text-regular-12 text-[#3F3FFF] border border-[--primary-500] border-inset rounded-2xl">
border-[--primary-500] ->  border-primary-500

2024-08-14 09:45 UTC, sikkzz commented on apps/meetie-service/src/app/confirm/page.tsx
> +          ></textarea>
닫는 태그로 변경

2024-08-14 09:45 UTC, sikkzz commented on apps/meetie-service/src/app/confirm/page.tsx
> +          <button className="w-full h-[50px] mt-6  mb-3 bg-[--primary-500] rounded-lg text-base text-white">
bg-primary-500

2024-08-14 09:45 UTC, sikkzz commented on apps/meetie-service/src/app/confirm/page.tsx
> +          <button className="w-full h-[50px] mt-6  mb-3 bg-[--primary-500] rounded-lg text-base text-white">
text-base는 무슨 속성인가요?

2024-08-14 09:45 UTC, sikkzz commented on apps/meetie-service/src/app/confirm/success/page.tsx
> +import React from "react";
제거

2024-08-14 09:45 UTC, sikkzz commented on apps/meetie-service/src/app/confirm/success/page.tsx
> +const ConfirmSuccess = () => {
export default function

2024-08-14 09:45 UTC, sikkzz commented on apps/meetie-service/src/app/confirm/success/page.tsx
> +    <>
fragment 제거

2024-08-14 09:45 UTC, sikkzz commented on apps/meetie-service/src/app/confirm/success/page.tsx
> +        </button>
todo 공통 버튼으로 변경 주석 추가

2024-08-14 09:45 UTC, sikkzz commented on apps/meetie-service/src/app/calendar/page.tsx
> +import React from "react";
제거

2024-08-14 09:45 UTC, sikkzz commented on apps/meetie-service/src/app/calendar/page.tsx
> +const Calendar = () => {
export default function

2024-08-14 09:45 UTC, sikkzz commented on apps/meetie-service/src/app/calendar/page.tsx
> +    <>
제거

2024-08-14 09:45 UTC, sikkzz commented on apps/meetie-service/src/app/calendar/page.tsx
> +          </div>
컴포넌트로 빼야할 거 같네요

2024-08-14 09:45 UTC, sikkzz commented on apps/meetie-service/src/app/calendar/page.tsx
> +          </div>
여기도 컴포넌트로 분리해주세요

2024-08-14 09:45 UTC, sikkzz commented on apps/meetie-service/src/app/confirm/[detail]/page.tsx
> +import React from "react";
제거

2024-08-14 09:45 UTC, sikkzz commented on apps/meetie-service/src/app/confirm/[detail]/page.tsx
> +const ConfirmDetail = () => {
변경

2024-08-14 09:45 UTC, sikkzz commented on apps/meetie-service/src/app/confirm/[detail]/page.tsx
> +          </div>
컴포넌트

2024-08-14 10:48 UTC, soyoung125 commented on apps/meetie-service/src/app/calendar/page.tsx
> +          <p className="border-b-2 border-[--primary-500] text-[--primary-500]">캘린더</p>
여기도 border-primary-500 text-primary-500로 적용가능헐 것 같습니다!

2024-08-14 10:48 UTC, soyoung125 commented on apps/meetie-service/src/app/calendar/page.tsx
> +              <p className="px-[13px] py-[8px] bg-[#F4F4F4] border border-[--primary-500] rounded-full">
컴포넌트로 분리하고 하이라이트 여부를 담는 props를 전달해서 테두리 색을 변경해주면 될 것같습니다.

2024-08-14 10:48 UTC, soyoung125 commented on apps/meetie-service/src/app/confirm/[detail]/page.tsx
> +      <section className="flex px-4 py-5 bg-[#FAFAFA] border-t border-b border-[#EFEFEF]">
댓글 카드도 컴포넌트로 분리하면 좋을 것 같습니다.

2024-08-14 10:48 UTC, soyoung125 commented on apps/meetie-service/src/app/confirm/page.tsx
> +        >
제가 global.css에 정의해 놨습니다! className에 hidden-scrollbar추가하시면 됩니당

2024-08-19 05:46 UTC, sikkzz requested changes

2024-08-19 05:46 UTC, sikkzz commented on apps/meetie-service/src/app/calendar/page.tsx
라우팅이 calendar가 아니라 study/room이 맞을 거 같아요

study 디렉토리 만들고 room 디렉토리도 만들어서 거기도 page.tsx 작성해 주세요

2024-08-19 05:46 UTC, sikkzz commented on apps/meetie-service/src/app/confirm/[detail]/page.tsx
> +            <Image src={UserImg} alt="user Imges" width={42} height={42} />
제가 avatar component 만든게 있는데 이후에 머지되면 사용하면 될 거 같아요 주석으로 todo만 적어주세요

2024-08-19 05:46 UTC, sikkzz commented on apps/meetie-service/src/app/confirm/page.tsx
버튼 컴포넌트 적용, 바텀 시트 팝업 모달 적용 등 todo를 적어주시면 좋을 거 같아요

2024-08-19 05:46 UTC, sikkzz commented on apps/meetie-service/src/app/confirm/success/page.tsx
여기도 button 적용 예정 todo

2024-08-19 09:33 UTC, sikkzz approved these changes

2024-08-19 09:34 UTC, ejinn1 approved these changes

2024-08-19 09:34 UTC, soyoung125 approved these changes

2024-08-19 09:40 UTC, detourguru approved these changes

2024-08-19 09:41 UTC, merged