3 front task main page publishing
Meetie-One/Meetie-front pull request #20
Opened 2024-08-14 04:39 UTC by detourguru

- [GITHUB ISSUE LINK]()

## 💡 변경사항 & 이슈
- 메인페이지 및 하위 페이지 퍼블리싱
<br>

## ✍️ 관련 설명
- 메인페이지 및 하위 페이지 퍼블리싱
- svg 컴포넌트화
<br>

## ⭐️ Review point
-  작업 편의를 위해 컴포넌트 쪼갠 단위가 좀 애매한것 같은데 의견 부탁드립니다 (FilteringMembers) 
<br>

## 📷 Demo
- 메인페이지
![image](https://github.com/user-attachments/assets/94458770-44d4-447a-a559-6264d7ecdc7c)
- 스터디 찾기 (메인에서 바로가기로 이동 || /explorer)
** 필터 버튼 눌러서 나오는 bottom sheet (임의 디자인) 
![image](https://github.com/user-attachments/assets/837ec620-0c11-4ba6-8684-47360e411d51)
![image](https://github.com/user-attachments/assets/049d0335-959a-4217-870b-2443c827baf2)
- 팀원 찾기
![image](https://github.com/user-attachments/assets/c1284f7d-be64-47b8-9ee6-2841b7f2e427)

<br>

2024-08-14 05:42 UTC, ejinn1 commented on apps/meetie-service/src/app/components/Badge.tsx
> +          </svg>
이 부분은 따로 svg 컴포넌트로 사용하지 않은 이유가 있나요??

2024-08-14 05:42 UTC, ejinn1 commented on apps/meetie-service/src/app/components/FilteringMembers.tsx
> +            />
다른 파일에서는 next/Image 사용했는데 여기에만 일반 img 태그를 사용한 이유가 따로 있을까요?

2024-08-14 05:42 UTC, ejinn1 commented on apps/meetie-service/src/app/explorer/page.tsx
> +function page() {
Page로 하는게 나을것 같습니다!

2024-08-14 05:42 UTC, ejinn1 commented on apps/meetie-service/src/app/explorer/page.tsx
> +  }
저희 이벤트 관련함수 컨벤션으로 정한게 handle이 맨 앞에 나오는걸로 정했어서

showSelectedTabHandler -> handleShowSelectedTab 이런 식으로 변경하는게 나을 것 같습니다!

2024-08-14 11:21 UTC, soyoung125 requested changes

2024-08-14 11:21 UTC, soyoung125 commented on apps/meetie-service/public/image/thinking_face.png
이미지 파일명 앞에 img_ 붙여주셔야 할 것 같습니다!

2024-08-14 11:21 UTC, soyoung125 commented on apps/meetie-service/src/app/components/FilteringMembers.tsx
> +          <div className="flex justify-center">
MemberCard내부도 컴포넌트 내부에 넣고 props로 이미지, 이름, 분야, 설명을 넘겨주면 코드가 간략해질 것 같아요!

2024-08-14 11:21 UTC, soyoung125 commented on apps/meetie-service/src/app/components/StudyCard.tsx
> +        <span className="bg-[#EBE9F5] text-[#41364A] text-medium-12 me-2 px-2.5 py-0.5 rounded">
태그들도 컴포넌트화하면 좋을 것 같습니다.

2024-08-18 14:06 UTC, jisong3377 commented on apps/meetie-service/public/image/thinking_face.png
이미지 컨벤션 svg파일과 동일하게 폴더명 img / img-arrow-down.png 와 같이 img 붙이고 언더바 대시로 바꾸셔야 할것같아용!

2024-08-18 14:06 UTC, jisong3377 commented on apps/meetie-service/src/app/components/FilteringMembers.tsx
> +export default FilteringMembers;
img 태그로 하신것들 next의 Image 컴포넌트로 바꾸셔야 할 것 같습니다 ~!

2024-08-19 05:19 UTC, sikkzz requested changes
이 내용들은 공통적으로 해당되는 리뷰입니다. 코드 전체 확인하면서 변경해주세요

1. 컨벤션 미준수
맞춘 컨벤션이랑 다른게 너무나도 많습니다. 아래 내용 이외에도 항상 신경써주세요
type
app router page는 export default function, 나머지 컴포넌트들은 const arrow function
svg 파일 Image 컴포넌트 사용

2. 컴포넌트 분리 미숙
이건 개발을 많이 해봐야 숙달되는 부분이지만 우선 현재 채연님 코드는
 - 컴포넌트 네이밍이 직관적이지 못해 한눈에 들어오지 않음
 - 분리해야하는 컴포넌트 단위를 정확히 파악하지 못하고 있음
 
네이밍이 어렵지만 직관적으로 작성해주시고 더 좋은 방법은 PR 내용에 적어주는 방법입니다만 양이 많으니 직관적으로 해주시는게 좋을 거 같아요

컴포넌트 단위는 정답을 설명드리기 어렵지만 보일때 마다 말씀드릴게요. 본인 파트 뿐만이 아닌 전체적인 파트를 확인하면서 재사용할 수 있는지, 더 효율적으로 나눠서 사용할 수는 없는지는 항상 고민하면서 개발하시는걸 추천드려요~

2024-08-19 05:19 UTC, sikkzz commented on apps/meetie-service/src/app/components/Badge.tsx
> +}
컨벤션 맞춰서 수정 부탁드려요

2024-08-19 05:19 UTC, sikkzz commented on apps/meetie-service/src/app/components/Badge.tsx
> +export default function Badge({ close, children, ...rest }: ISpanProps) {
...rest 말고 ...props로 사용 부탁드려요

큰 차이점이 있는건 아니지만 직관적인 네이밍 차이라고 보시면 될 거 같습니다

2024-08-19 05:19 UTC, sikkzz commented on apps/meetie-service/src/app/components/Badge.tsx
Badge 보다 HashTag가 네이밍이 더 어울릴 거 같아요

Tag는 이미 제가 써버려서요

2024-08-19 05:19 UTC, sikkzz commented on apps/meetie-service/src/app/components/Filter.tsx
제가 27번 브랜치에 바텀 시트 팝업 모달 만든거 있는데 그 양식으로 쓰는게 좋아 보입니다. 추후 머지되면 로직 수정해주세요

해당 브랜치에서는 냅둬야 할 듯 합니다.

2024-08-19 05:19 UTC, sikkzz commented on apps/meetie-service/src/app/components/FilteringMembers.tsx
얘를 MemberList 컴포넌트로 두고 내부에 Member 컴포넌트를 만들면 간소화가 쉬워질 거 같네요

2024-08-19 05:19 UTC, sikkzz commented on apps/meetie-service/src/app/components/FilteringMembers.tsx
> +        <MemberCard>
여기 겹치는 코드들 위에 알려드린 방법대로 간소화 시켜야할 거 같아요

2024-08-19 05:19 UTC, sikkzz commented on apps/meetie-service/src/app/components/FilteringStudies.tsx
파일명과 컴포넌트명이 달라야할 이유는 없어 보입니다 통일 부탁드려요

2024-08-19 05:19 UTC, sikkzz commented on apps/meetie-service/src/app/components/FilteringStudies.tsx
이건 이렇게 구현할 부분이 아니라 아래 두 사진이 다른 컴포넌트로 나뉘는게 맞을 거 같아요

굳이 내부에서 children의 여부로 구현할 필요가 없을뿐더러 두개는 다른 기능을 하는 컴포넌트들이기에 분리되는게 맞습니다

<img width="107" alt="스크린샷 2024-08-19 오후 2 08 02" src="https://github.com/user-attachments/assets/a00494e4-fb36-4ca2-9940-a6389e2de66e">
<img width="42" alt="스크린샷 2024-08-19 오후 2 08 08" src="https://github.com/user-attachments/assets/1774776f-c4ef-498e-baee-9981000b85c8">

2024-08-19 05:19 UTC, sikkzz commented on apps/meetie-service/src/app/components/MemberCard.tsx
> +    <>
Fragment 없어도 될 거 같네요

2024-08-19 05:19 UTC, sikkzz commented on apps/meetie-service/src/app/components/StudyCard.tsx
> +        <span className="bg-[#EBE9F5] text-[#41364A] text-medium-12 me-2 px-2.5 py-0.5 rounded">
제가 만든 Tag 공통 컴포넌트 있습니다. 주석으로 변경 예정만 달아주시고 이후에 적용시켜주세요

2024-08-19 05:19 UTC, sikkzz commented on apps/meetie-service/src/app/components/ToggleSwitch.tsx
Toggle도 공통으로 만드는게 좋을 거 같네요. 소영님꺼랑 같이 확인하면서 제가 이후에 만들어 드릴게요

todo로 기재만 해주세요

2024-08-19 05:19 UTC, sikkzz commented on apps/meetie-service/src/app/explorer/page.tsx
메인 페이지를 use client를 쓰는건 어쩔 수 없는게 아니라면 안쓰는게 좋습니다.

현재 상황에서는 컴포넌트 분리만 더 잘한다면 굳이 최상단 page에서 use client가 들어갈 이유가 없어보이네요

2024-08-19 05:19 UTC, sikkzz commented on apps/meetie-service/src/app/explorer/page.tsx
> +function page() {
export default function

2024-08-19 05:19 UTC, sikkzz commented on packages/meetie-design-system/vite.config.ts.timestamp-1723092293977-31564a6c56f0f.mjs
이거 파일 지워주세요 왜 들어간건지는 모르겠긴 한데

2024-08-19 07:45 UTC, detourguru commented on apps/meetie-service/src/app/explorer/page.tsx
tab 컴포넌트 분리

2024-08-19 08:35 UTC, sikkzz approved these changes

2024-08-19 08:36 UTC, ejinn1 approved these changes

2024-08-19 09:14 UTC, jisong3377 approved these changes

2024-08-19 09:14 UTC, soyoung125 approved these changes

2024-08-19 09:15 UTC, merged