18 front task apply my page icon
Meetie-One/Meetie-front pull request #23
Opened 2024-08-16 15:40 UTC by soyoung125

- [GITHUB ISSUE LINK]()

## 💡 변경사항 & 이슈
마이페이지 아이콘 적용
<br>

## ✍️ 관련 설명
준식님의 공통 버튼 컴포넌트 코드를 참고하며 뱃지 아이콘 컴포넌트를 제작했습니다.
뱃지 이미지의 색상은 css의 mix-bled-mode hue를 적용한 블록을 아이콘과 중첩시켜 특정 색상이 적용되도록 구현했습니다.

size props (width, height)
default -> 78px
sm -> 29px
md-> 73px
lg -> 95px
xl -> 143px

variant props (color)
default -> bg-primary-500 (#6224fd)
secondary -> bg-primary-400 (#8655ff)
tertiary -> bg-[#0F0F0F]

뱃지 아이콘 외에도 마이페이지, 프로필 수정 페이지, 능력 현황 페이지에 사용되는 아이콘을 추가했습니다.
또한, 공통 컴포넌트인 Header와 Gnb 적용을 완료했습니다.

ability 페이지와 profile 페이지 헤더의 LeftButton 아이콘이 안보이는 문제는 해당 pr에 리뷰 남겨놨습니다.
<br>

## ⭐️ Review point
테스트 해보시고 수정해야 할 부분이나 추가되어야 하는 아이콘이 있다면 말씀해주세요.
<br>

## 📷 Demo

/mypage

![image](https://github.com/user-attachments/assets/53dfb239-7506-4706-864d-00609140ff6c)

/mypage/profile

![image](https://github.com/user-attachments/assets/a25138f1-b405-4b75-9685-09363007658a)

/mypage/ability

![image](https://github.com/user-attachments/assets/e1ee4c20-9450-44ca-a811-ea0fd6295ec7)

2024-08-17 06:53 UTC, sikkzz requested changes

2024-08-17 06:53 UTC, sikkzz commented on apps/meetie-service/src/app/mypage/ability/page.tsx
> +import ClockIcon from "@/components/MyPage/Clockcon";
오타 있네요

2024-08-17 06:53 UTC, sikkzz commented on apps/meetie-service/src/components/MyPage/BadgeIcon/BadgeIcon.tsx
> +    <>
Fragment 삭제

2024-08-17 06:53 UTC, sikkzz commented on apps/meetie-service/src/components/MyPage/BadgeIcon/BadgeIcon.tsx
> +        <Image {...props} priority={true} />
priority만 명시해도 동일할 거 같아요

2024-08-17 06:53 UTC, sikkzz commented on apps/meetie-service/src/components/MyPage/BadgeIcon/BadgeIcon.tsx
> +        <div className={cn(badgeIconVariants({ variant, size }))}></div>
닫는 태그로 변경

2024-08-17 06:53 UTC, sikkzz commented on apps/meetie-service/src/components/MyPage/Clockcon.tsx
파일명 오타같아 보여서 확인 및 수정 부탁드려요

2024-08-17 07:44 UTC, ejinn1 commented on apps/meetie-service/src/components/MyPage/Profile/HighlightBadge/HighlightBadge.tsx
>      >
border-primary-${selected ? "450" : "200"} 이렇게 사용하면 제가 알기로 아마 적용이 안될거에요
${selected ? "border-primary-450" : "border-primary-200"} 으로 해야 적용될거에욥

2024-08-18 10:09 UTC, ejinn1 approved these changes

2024-08-19 03:52 UTC, jisong3377 approved these changes

2024-08-19 04:14 UTC, detourguru approved these changes

2024-08-19 05:21 UTC, sikkzz approved these changes

2024-08-19 06:06 UTC, merged