22 front task apply icons and components to onboarding
Meetie-One/Meetie-front pull request #24
Opened 2024-08-17 05:52 UTC by ejinn1

- https://github.com/Meetie-One/Meetie-front/issues/22

## 💡 변경사항 & 이슈
온보딩 과정 이미지 및 아이콘 적용
<br>

## ✍️ 관련 설명
이미지를 svg로 적용시켰습니다.
사용한 버튼은 공통 버튼 컴포넌트로 변경했습니다.
뱃지 아이콘은 소영님꺼 공통 컴포넌트를 사용할 예정입니다.
TagButton, Gnb 컴포넌트에 아이콘 안보이는 문제는 이 브랜치에서 수정했습니다.
`/onBoarding/complete` 페이지에서 애니메이션도 적용시켰습니다.

사진을 대부분 svg로 작업했는데 png파일로 불러오려면 피그마에 있는 원본보다 크게 가져와서 작업해야 화질이 안깨지더라구요 인터넷 서치하니까 svg사용하면 용량도 적고 크기 변환에도 화질이 안깨져서 svg사용했는데 의견 남겨주시면 감사하겠습니다

<br>

## ⭐️ Review point
수정해야될 부분이나 적용이 안된 아이콘이나 이미지가 있으면 말씀해주세요

<br>

## 📷 Demo
### `/`
<img width="445" alt="image" src="https://github.com/user-attachments/assets/a6195d48-9d90-4085-bec9-2fec8d886f0f">

### `/login`
<img width="375" alt="image" src="https://github.com/user-attachments/assets/96d4ba8c-e7a0-4cad-8f42-e134955463b2">

### `/walkThrough`
<img width="374" alt="image" src="https://github.com/user-attachments/assets/657e3e3c-ab40-4aec-9791-2760f8b05fc7">

### `/onBoarding`
- `/job`
<img width="360" alt="image" src="https://github.com/user-attachments/assets/33498593-fa07-4dee-a0f8-394ee9ed258d">

- `/purpose`
<img width="361" alt="image" src="https://github.com/user-attachments/assets/1a863853-244c-4cf5-bd77-0c046691137d">

- `/style`
<img width="357" alt="image" src="https://github.com/user-attachments/assets/19f05384-8105-40c9-b103-b70d09f7eeb8">

- `/period`
<img width="355" alt="image" src="https://github.com/user-attachments/assets/8b0391d7-afd4-45b9-8361-68bd9f904d54">

- `/complete`
<img width="313" alt="image" src="https://github.com/user-attachments/assets/6d4bf480-052f-4776-b825-c17b6e247338">

<br>

2024-08-18 09:25 UTC, soyoung125 approved these changes

2024-08-19 05:56 UTC, sikkzz requested changes

2024-08-19 05:56 UTC, sikkzz commented on apps/meetie-service/src/app/login/page.tsx
여기는 우선 리뷰 안할게요. 사용 여부에 따라 이후에 다시 리뷰 하던가 할게요 지우지는 마세요!

2024-08-19 05:56 UTC, sikkzz commented on apps/meetie-service/src/app/onBoarding/[step]/page.tsx
> +          <Button variant="outline" size="sm" onClick={() => handlePrevStep()}>
onClick={handleNextStep}

2024-08-19 05:56 UTC, sikkzz commented on apps/meetie-service/src/app/onBoarding/[step]/page.tsx
> +          <Button onClick={() => handleNextStep()}>
onClick={handleNextStep}

2024-08-19 05:56 UTC, sikkzz commented on apps/meetie-service/src/constants/onBoarding.ts
constants들은 DATA를 붙이는걸 추천드려요~

2024-08-19 07:09 UTC, ejinn1 commented on apps/meetie-service/src/app/login/page.tsx
넵

2024-08-19 07:10 UTC, ejinn1 commented on apps/meetie-service/src/constants/onBoarding.ts
DATA 붙히는걸로 수정했습니다 따로 title 컴포넌트 만들어서 가져다가 사용하는 걸로 수정했습니다

2024-08-19 09:18 UTC, detourguru commented on apps/meetie-service/src/app/login/page.tsx
>      "py-[14px] px-[16px] text-regular-16 placeholder:text-gray-200 border border-gray-100 rounded-lg w-full outline-none";
이건 그냥 궁금한건데 border 하고 outline-none하면 무슨 효과가 적용되나여 ? 보기로는  차이 없어보여서요

2024-08-19 09:19 UTC, detourguru approved these changes

2024-08-20 00:45 UTC, jisong3377 approved these changes

2024-08-20 01:33 UTC, sikkzz approved these changes

2024-08-20 05:37 UTC, soyoung125 commented on apps/meetie-service/src/app/onBoarding/complete/page.tsx
> +                <div className="absolute w-[80px] h-[80px] bg-blue-400 mix-blend-hue z-10" />
```
<div className="relative flex justify-center w-full transform animate-tilt backdrop-blur-[2px]">
  <div className="w-[146px] h-[204px] border rounded-lg bg-[#FAFAFF]/70" />
  <div className="absolute top-0 flex flex-col items-center justify-center pt-6 whitespace-nowrap">
    <div className="relative w-[80px] h-[80px] flex justify-center bg-gradient-to-tr from-[#FAFAFF]/60 to-[#FAFAFF]/45">
      <div className="absolute w-[80px] h-[80px] bg-[#0017E2] mix-blend-hue z-10" />
```
어제 물어보신거 이렇게 하니까 어느정도 피그마랑 비슷해지는 것 같습니당
![image](https://github.com/user-attachments/assets/525d32af-6a08-4ecc-82a5-945a0d3f43b8)

2024-08-20 06:34 UTC, merged