29 front task study detail page publishing
Meetie-One/Meetie-front pull request #30
Opened 2024-08-18 09:42 UTC by sikkzz

- [https://github.com/Meetie-One/Meetie-front/issues/29](https://github.com/Meetie-One/Meetie-front/issues/29)

## 💡 변경사항 & 이슈
스터디 상세 화면 퍼블리싱
스터디 대기중인 요청 화면 퍼블리싱

## ✍️ 관련 설명
스터디 상세 화면 퍼블리싱
스터디 대기중인 요청 화면 퍼블리싱
Tag 컴포넌트 추가
Avatar 컴포넌트 추가
study-create route 변경

## ⭐️ Review point
스터디 생성 페이지 -> /study/create
스터디 상세 페이지 -> /study/[id]
스터디 대기중인 요청 페이지 -> /study/[id]/request

컴포넌트 구조나 내부 요소 구성은 기능 구현 및 api 연결시 변경 될 수 있음
이외에 디자인도 피그마와 조금 다른 부분 존재 (여백이 안맞거나 홀수 값들 임의 조정)

## 📷 Demo
<img width="363" alt="스크린샷 2024-08-18 오후 6 41 59" src="https://github.com/user-attachments/assets/7f2fdec3-ef25-48fa-a495-762fa1b5e9f7"> -> /study/1

<img width="367" alt="스크린샷 2024-08-18 오후 6 42 22" src="https://github.com/user-attachments/assets/4e809efd-c760-4cc5-ad8b-bf9a7552953e"> -> /study/1/request

2024-08-19 09:27 UTC, soyoung125 requested changes

2024-08-19 09:27 UTC, soyoung125 commented on apps/meetie-service/src/components/Study/StudyDetail/FooterBtn/FooterBtn.tsx
> +    <div className="fixed bottom-0 bg-white px-4 py-6 flex gap-5 items-center">
중요한 건 아니지만 border-top이 누락된 것 같습니다!

2024-08-19 09:27 UTC, soyoung125 commented on apps/meetie-service/src/app/study/[id]/request/page.tsx
> +      <StudyRequestCard date="2024년 06월 08일" />
카드들을 묶어서 padding-bottom을 줘야 FooterBtn에 카드가 잘리지 않고 보일 것 같습니다!

2024-08-20 00:24 UTC, detourguru commented on apps/meetie-service/src/components/Study/CreateStudy/CreateStudySecondStep.tsx
> +            <Image src="/svg/ic-study-minus.svg" alt="downArrowIcon" width={16} height={16} />
alt가 사진과 맞지않는것 같아용

2024-08-20 01:25 UTC, jisong3377 commented on apps/meetie-service/src/components/Study/StudyDetail/FooterBtn/FooterBtn.tsx
> +export default FooterBtn;
버튼을 컴포넌트로 빼서 문구가 동일한건가 보네요 props로 처리하실건가욥

2024-08-20 01:39 UTC, jisong3377 commented on apps/meetie-service/src/components/Study/StudyDetail/FooterBtn/FooterBtn.tsx
> +        <p className="text-bold-16 text-white">아직 대기 인원이 없습니다</p>
버튼을 컴포넌트로 빼서 상세/대기요청 문구가 동일한건가 보네요 props로 처리하실건가욥

2024-08-20 02:01 UTC, sikkzz commented on apps/meetie-service/src/components/Study/StudyDetail/FooterBtn/FooterBtn.tsx
> +        <p className="text-bold-16 text-white">아직 대기 인원이 없습니다</p>
이후에 기능 구현하면서 조건부 처리랑 disabled 처리까지 다 할 예정이에요

2024-08-20 05:39 UTC, soyoung125 approved these changes

2024-08-20 06:25 UTC, ejinn1 approved these changes

2024-08-20 06:36 UTC, merged