46 front task feat edit profile
Meetie-One/Meetie-front pull request #48
Opened 2024-08-21 23:16 UTC by soyoung125

- [GITHUB ISSUE LINK]()

## 💡 변경사항 & 이슈
프로필 수정 이벤트 핸들러 적용
<br>

## ✍️ 관련 설명
프로필 데이터를 state로 관리

유저 프로필 이미지, 이름, 자기소개, 대표 뱃지 설정, 스터디 태그 추가/삭제 구현

상태를 전역 상태로 관리하거나 db에 넣는 로직은 구현하지 않았기 때문에 새로고침 시 데이터가 사라집니다.

대표 뱃지 설정에서 뱃지의 레벨은 뱃지 달성 기준 확립 후 레벨이 변동될 수 있도록 구현할 예정입니다.

스터디 경험에서 스터디 공개 유무를 설정하는 로직은 미구현입니다. DB 스키마도 생각해서 구현해야 할 것 같아서 구현을 못했습니다.
<br>

## ⭐️ Review point
테스트 해보시고 예외 상황이 발생하거나 디자인 적인 문제가 발견된다면 말씀해주시길 바랍니다.
<br>

## 📷 Demo

https://github.com/user-attachments/assets/9353f317-f3f0-42d0-b043-61a593c6f752

<br>

2024-08-22 03:17 UTC, ejinn1 commented on src/app/user/[id]/edit/page.tsx
> +              <Image src={"/svg/ic-camera.svg"} alt="camera" width={16} height={16} />
중괄호 빼도 될거같아요 
src="/svg/ic-camera.svg" 요렇게

2024-08-22 03:58 UTC, sikkzz requested changes
말씀드린 sharp랑 빌드도 확인 부탁드려요~

2024-08-22 03:58 UTC, sikkzz commented on src/app/user/[id]/edit/page.tsx
> +    const file = e.target.files && e.target.files[0];
하나의 객체 state에서 값 업데이트 함수를 하나로 할 수 있는 방법이 있습니다

아래 사진들이 제가 사용하는 방식인데 한번 해보시고 어렵거나 작동에 문제있으면 말씀해주세요 도와드릴게요

이렇게 해서 state, handleUpdate 함수, submit 함수까지 해서 hook으로 분리해서 써야 UI 로직과 비즈니스 로직의 분리가 확실해요

<img width="542" alt="스크린샷 2024-08-22 오후 12 51 35" src="https://github.com/user-attachments/assets/ea3d4918-17aa-4743-aad9-e805b47b16e6">
<img width="533" alt="스크린샷 2024-08-22 오후 12 51 31" src="https://github.com/user-attachments/assets/e7853ede-76c3-4b50-ae9d-009b050382eb">

2024-08-22 03:58 UTC, sikkzz commented on src/app/user/[id]/edit/page.tsx
> +    profileImage: "",
원래는 백엔드에서 처리해야 좋지만 저희가 백엔드를 동시에 하니까 default Image 처리도 신경쓰면 좋을 거 같아요

DB에서 데이터를 가져왔을 때 profileImage에 image가 없을 경우 default Image 하나를 여기서 처리해주는게 좋을 거 같네요

2024-08-22 05:29 UTC, soyoung125 commented on src/app/user/[id]/edit/page.tsx
> +    const file = e.target.files && e.target.files[0];
제가 최대한 구현해 봤는데 수정해야 할 곳이 있는지 봐주시길 바랍니다.ㅜ

2024-08-22 05:29 UTC, soyoung125 commented on src/app/user/[id]/edit/page.tsx
> +    profileImage: "",
새로운 user icon 추가했습니다!

2024-08-22 08:21 UTC, sikkzz requested changes

2024-08-22 08:21 UTC, sikkzz commented on src/app/user/[id]/edit/page.tsx
Avatar 컴포넌트 코드 아래 사진처럼 수정 부탁드려요

직사각형, 정사각형 이미지들이 들어갈때 현재는 사이즈가 꺠지네요. 해당 코드 넣어보고도 문제 있으면 한번 더 말씀해주세요

<img width="561" alt="스크린샷 2024-08-22 오후 5 18 30" src="https://github.com/user-attachments/assets/9939dbe8-2da7-44a6-824b-4246f91df56a">

2024-08-22 08:24 UTC, sikkzz commented on src/app/user/[id]/edit/page.tsx
> +    const file = e.target.files && e.target.files[0];
로직상에는 문제가 없어 보여요

더 깔끔하게 하려면 hook으로 분리하고 initialdata 이용해서 api로 받아오는 초기값을 구분해주면 될 거 같아요

제꺼 52번 브랜치 CreateStudyPage, useCreateStudyForm 코드 참고하셔보세요. 수정 로직은 기존값 데이터가 있기 때문에 initialdata 여부에 대한 처리가 필요할테니까요

2024-08-22 08:26 UTC, sikkzz commented on src/app/user/[id]/edit/page.tsx
> +    const file = e.target.files && e.target.files[0];
원래 initialData 여부를 판단해서 create와 update 로직을 동일한 로직으로 재사용할 수 있기 때문에 hook으로 분리해서 C,U 로직에 동시에 사용하는거도 있지만 코드 로직 분리를 통한 간결함을 생각하면 분리하는게 좋을 거 같아요

이후 data fetching 코드도 추가될 거고 로딩 ui, api error 로직 등 로직이 추가 될 가능성은 매우 다양하니까요

2024-08-22 09:26 UTC, soyoung125 commented on src/app/user/[id]/edit/page.tsx
잘 동작합니다!
![image](https://github.com/user-attachments/assets/ec2ac25d-ef97-4181-9aea-c9d5f2f2bd78)

2024-08-22 09:27 UTC, soyoung125 commented on src/app/user/[id]/edit/page.tsx
> +    const file = e.target.files && e.target.files[0];
useEditProfileForm 훅 추가했습니다.

2024-08-22 09:38 UTC, sikkzz approved these changes

2024-08-23 01:19 UTC, jisong3377 commented
태그 만들 때 maxlength 안줘도 될까요? 보통 제한 없지만 태그에 테두리가 있으니까 코멘트 남겨봅니당

2024-08-23 01:21 UTC, jisong3377 approved these changes

2024-08-23 02:38 UTC, detourguru approved these changes

2024-08-23 05:13 UTC, ejinn1 approved these changes

2024-08-23 05:44 UTC, merged