44 front task feat onboarding
Meetie-One/Meetie-front pull request #49
Opened 2024-08-22 01:15 UTC by ejinn1

- https://github.com/Meetie-One/Meetie-front/issues/44

## 💡 변경사항 & 이슈
온보딩 과정 구현
<br>

## ✍️ 관련 설명
온보딩 주소를 `/onboarding`으로 통합
직무, 목적, 스타일, 기간을 설정해서 프로필 생성 구현

route.ts부분은 db연동 되면 수정할 예정입니다.
유저 정보 부분도 로그인 기능 구현되면 적용시킬 예정입니다.

db 테이블도 추후에 연동 되면 만들어야할 것 같습니다.
<br>

## ⭐️ Review point
로직 상의 문제가 있으면 말씀해주세요
<br>

## 📷 Demo

https://github.com/user-attachments/assets/0beb3f75-1a91-4f90-a045-e8a692811acf

<br>

2024-08-23 06:27 UTC, soyoung125 commented on src/app/onboarding/page.tsx
> +  };
onbordinForm으로 하나의 상태로 관리하면 코드가 더 짧아질 수 있지 않을까 싶습니다
그러면 buttonVariant를
```
if (form[step].length === 0) {
  return "disabled"
}
```
이렇게 하나로 줄일 수 있을 것 같아요.

2024-08-23 10:08 UTC, sikkzz requested changes

2024-08-23 10:08 UTC, sikkzz commented on src/app/onboarding/complete/page.tsx
> +  const result = await response.json();
함수로 모듈화해서 쓰는게 좋을 거 같아요 todo로 작성 하나만 해주세요

데이터 fetching 라이브러리 쓸지 안쓸지 여부에 따라 모듈화 방식 추후에 정해볼게요

2024-08-23 10:08 UTC, sikkzz commented on src/app/onboarding/page.tsx
> +  const [period, setPeriod] = useState<string>("");
todo 주석으로 객체화 state 사용, hook으로 분리 적어주세요

구두 논의 했던대로 리팩토링은 이후 브랜치에서 진행해주시면 됩니다

2024-08-23 10:08 UTC, sikkzz commented on src/app/onboarding/page.tsx
> +  };
소영님 의견에는 동의합니다. 다만 제가 코드를 잘 이해한게 맞다면 내용이 비어있을시 button disabled 처리를 해주는 로직 같은데,
variant default 기준 버튼이 disabled일때 디자인 처리를 제가 해놓았습니다.

해당 경우에서는 데이터 값의 isEmpty 여부를 체크한 후 아래 코드처럼 사용하는게 더 좋아 보여요

```jsx
const isEmpty = purpose.length === 0

<Button disabled={isEmpty}>버튼</Button>
```

이러면 data empty 여부에 따라 버튼 disabled 여부도 따라올거에요

2024-08-23 10:08 UTC, sikkzz commented on src/app/onboarding/page.tsx
> +  };
버튼 disabled 옵션을 사용하면 onClick handler 포함해서 어떤 상호작용도 일어나지 않습니다.

그렇다면 저렇게 추가적인 handler 예외처리를 할 필요 없겠죠?

2024-08-23 10:08 UTC, sikkzz commented on src/app/onboarding/page.tsx
> +    }
여기도 불필요할거에요 제 리뷰대로 한다면

2024-08-23 10:08 UTC, sikkzz commented on src/app/onboarding/page.tsx
> +  };
이부분도 todo 주석으로 모듈화 하나만 적어주세요

2024-08-23 10:08 UTC, sikkzz commented on src/app/onboarding/page.tsx
> +        {step === "period" && <FourthStep clickedPeriod={period} setPeriod={setPeriod} />}
setState 함수를 props로 바로 넘겨주는건 매우 안좋은 선택입니다

구글링시 더 자세하게 나오겠지만 제가 기억하는 바로는 state의 불변성을 어긋나게 한다고 알고 있어요

하위 컴포넌트에서 상위 state값을 변경하고 싶다면 handler 함수로 작성해서 그 handler를 props로 넘겨줘야 합니다

2024-08-23 10:08 UTC, sikkzz commented on src/app/onboarding/page.tsx
> +            variant={buttonVariant()}
여기 disabled 처리 한번 해보시면 차이점을 보실 수 있습니다

2024-08-23 12:01 UTC, detourguru commented on src/app/api/onboarding/route.ts
> +    return new Response(JSON.stringify({ message: "error", status: 500 }));
물론 나중에 로직 구현 시에 구체화되겠지만 "error" 를 에러메시지로 반환하기보다는 err 로 반환되는 에러를 에러 메시지로 내어 주고 status도 서버에서 내려오는 에러코드를 반환하는게 디버깅이 용이할 것 같습니다!

2024-08-23 13:58 UTC, jisong3377 approved these changes

2024-08-24 04:49 UTC, ejinn1 commented on src/app/onboarding/page.tsx
> +  };
넵 인정합니다

2024-08-24 05:59 UTC, ejinn1 commented on src/app/onboarding/page.tsx
> +  };
다음 브랜치에서 합쳐서 리펙토링 해볼게요

2024-08-24 10:28 UTC, sikkzz approved these changes

2024-08-25 06:09 UTC, soyoung125 approved these changes

2024-08-26 03:44 UTC, detourguru approved these changes

2024-08-26 03:55 UTC, merged