36 front task apply common components to studylist
Meetie-One/Meetie-front pull request #54
Opened 2024-08-22 07:05 UTC by detourguru

- [GITHUB ISSUE LINK](https://github.com/Meetie-One/Meetie-front/issues/36)

## 💡 변경사항 & 이슈
- 공통 컴포넌트 적용 (tag)
- 절대경로로 경로 수정
- bottom sheet 스타일링 통일
- 이미지에 hue blend 적용

✍️ 관련 설명
- 공통 컴포넌트를 적용할 수 있는 tag 부분 공통 컴포넌트로 대체
- import 상대경로 절대 경로로 수정
- bottom sheet 스타일링 jobsheet와 통일

## ⭐️ Review point
- #3 이슈에서 리뷰받은 마이너한 부분에 대한 수정이 일어났습니다 근데 42번 브랜치랑 작업이 겹친게 좀 있네요
<br>

## 📷 Demo
![image](https://github.com/user-attachments/assets/f4d36e42-4339-4bce-bc7a-2a5ac5a5105c)

<br>

2024-08-22 08:27 UTC, sikkzz commented
42 리베이스 부탁드려요

2024-08-22 09:44 UTC, sikkzz requested changes

2024-08-22 09:44 UTC, sikkzz commented on src/components/Study/Explorer/FilterSheet.tsx
1. 우선 현재 select 메뉴 뜨는 위치 이상합니다.
2. calendar는 제가 현재 공통 컴포넌트로 뽑고 있어서 이후에 이거 적용시키는게 좋을 거 같아요

다만 현재 수정은 안하셔도 됩니다. 디자인적으로 컨펌좀 드리고 싶은데 여유 있을때 다시 말씀 드릴게요

해당 파일 추가적인 코드 리뷰도 이후에 하겠습니다. 바텀 시트 팝업으로 로직 뜨는건 문제 없으니까요

2024-08-23 05:59 UTC, ejinn1 commented on src/components/Study/Explorer/FilterSheet.tsx
> +                />
px-2 py-2를 p-2로 수정하는게 나을거같습니당

2024-08-23 05:59 UTC, ejinn1 commented on src/components/Study/Explorer/FilterSheet.tsx
> +                />
아래에도 공통으로 수정해주세요

2024-08-23 05:59 UTC, ejinn1 commented on src/components/Study/Explorer/FilterSheet.tsx
> +                </label>
따로 이유가 있는거 아니면 stone보다 저희가 정의해둔 gray를 쓰는게 통일감 있을거같습니당

2024-08-23 05:59 UTC, ejinn1 commented on src/components/Study/Explorer/FilterSheet.tsx
> +    <>
<></> 부분 없어도 될거같아요

2024-08-23 06:48 UTC, soyoung125 commented on src/components/Study/Explorer/FilterSheet.tsx
> +                  className="mt-2 block w-full rounded-md border border-gray-200 px-2 py-2 shadow-sm outline-none focus:border-blue-500 focus:ring focus:ring-blue-200 focus:ring-opacity-50"
block w-full 은 없어도 문제가 없는 것 같습니다!

2024-08-23 06:48 UTC, soyoung125 commented on src/components/Study/Explorer/ExplorerTab.tsx
>            <div className="-mr-4 -ml-4 mb-4 bg-[#F2F2F2] h-2"></div>
-mr-4 -ml-4를 -mx-4로 수정하는 게 나을 것 같습니다.

2024-08-23 09:52 UTC, jisong3377 commented on src/components/Study/Explorer/FilterSheet.tsx
> +                <label htmlFor="manufacturer" className="text-stone-600 text-bold-16">
여기도 stone 있어욥 (gray 통일 의견)

2024-08-28 03:54 UTC, ejinn1 approved these changes

2024-08-28 04:01 UTC, sikkzz commented
이거 제가 65번 브랜치에서 수정한 부분들이 있어서 그거 먼저 머지되고 rebase하는 방향으로 해야할 거 같네요

기본적인 콘솔 warning이나 이런거도 수정해놓은 상태라서요

2024-08-28 13:52 UTC, soyoung125 approved these changes

2024-08-29 07:12 UTC, sikkzz requested changes

2024-08-29 07:12 UTC, sikkzz commented on src/components/Study/Explorer/ExplorerTab.tsx
lint 에러 있네요

2024-08-30 03:33 UTC, sikkzz requested changes

2024-08-30 03:33 UTC, sikkzz commented on src/components/Study/StudyRoomList/StudyCard.tsx
> +          {studyData.tagList?.map((tag) => <Tag text={tag} isSmall key={tag} />)}
이거 옵셔널이 왜들어갔을까요?

2024-08-30 03:37 UTC, detourguru commented on src/components/Study/StudyRoomList/StudyCard.tsx
> +          {studyData.tagList?.map((tag) => <Tag text={tag} isSmall key={tag} />)}
이거 필드 보면 not null이고 db에도 실제로 null값인 데이터는 없는데 아래처럼 에러뜨길래 일단 추가했습니다
![image](https://github.com/user-attachments/assets/dfe28a50-29fe-44a7-9edd-93b014372404)

2024-08-30 03:41 UTC, sikkzz commented on src/components/Study/StudyRoomList/StudyCard.tsx
> +          {studyData.tagList?.map((tag) => <Tag text={tag} isSmall key={tag} />)}
아 스터디 리스트는 제가 api 수정을 따로 안했네요 이거 이후 브랜치에서 제가 해놓을게요 우선 확인했습니다

에러가 나는 이유는 필드가 nullable인데 현재 db에는 null값인 데이터가 존재합니다. 이에 대한 예외처리를 안해놓긴 했네요

다만 옵셔널을 사용하는건 좋은 방법이 아닙니다. studyData.tagList가 있는지에 대한 조건 연산을 넣는게 정석이에요

2024-08-30 03:44 UTC, detourguru commented on src/components/Study/StudyRoomList/StudyCard.tsx
> +          {studyData.tagList?.map((tag) => <Tag text={tag} isSmall key={tag} />)}
오잉 nullable이군요 제가 잘못봤나바여 내용 확인했습니다

2024-08-30 03:54 UTC, sikkzz approved these changes

2024-08-30 03:59 UTC, jisong3377 approved these changes

2024-08-30 04:00 UTC, merged