53 front task modify page path in mypage
Meetie-One/Meetie-front pull request #56
Opened 2024-08-22 07:43 UTC by soyoung125

- [GITHUB ISSUE LINK]()

## 💡 변경사항 & 이슈
마이 페이지 메뉴 아이템 라우팅 경로 수정
내 정보 카드 페이지 라우팅 적용
메뉴 아이템 데이터 상수로 관리
<br>

## ✍️ 관련 설명
마이 페이지에서 메뉴 아이템의 라우팅 경로를 수정했습니다. 
- USER_FOLLOW_LIST 추가
  - 내정보/친구 클릭 시 이동
- INTEREST_RECENT_VISIT 제거
  - 최근 방문이어서 PATH.STUDY 사용
- 키 변경
  - JOINING_STUDY -> STUDY_JOINING_LIST
  - LAST_STUDY -> STUDY_LAST_LIST
  - INTEREST -> STUDY_INTEREST_LIST

메뉴 아이템 데이터를 상수로 관리할 수 있도록 분리했습니다.

계정 정보 - 회원 정보 수정의 라우팅 경로를 user/[id]에서 user/[id]/edit으로 변경햇습니다.

내 정보에서 각각의 카드를 선택 시 해당 페이지로 이동할 수 있도록 코드를 추가했습니다.
<br>

## ⭐️ Review point
코드 라인수를 줄이고 싶어서 메뉴 아이템 데이터를 상수로 분리했는데, 가독성이 괜찮은지 모르겠네요. 코드 수정할 부분이 있다면 말씀해주시길 바랍니다.
<br>

## 📷 Demo

<br>

2024-08-23 06:39 UTC, ejinn1 approved these changes

2024-08-23 09:39 UTC, sikkzz requested changes

2024-08-23 09:39 UTC, sikkzz commented on src/components/MyPage/MenuListItem/MenuListItem.tsx
>  import Toggle from "../Toggle/Toggle";
절대경로

2024-08-23 09:42 UTC, sikkzz commented
코드 라인수를 줄이기 위한 상수화도 저는 의미를 두는 편이지만 상수로 다른 파일에 빼서 사용하는 가장 큰 이유는 저는 실수를 줄이기 위해서라고 생각해요

UI의 수정이 필요해서 코드를 변경하다 의도치 않은 실수 발생, 이로 인한 디버깅 에러와 다른 오류들이 일어날 수 있는 여지를 최대한 줄인다고 생각하면 좋을 거 같아요

저는 백엔드와 협업할 때 api 요청이 추가로 일어나는 단점이 있지만 저런 상수들도 고정적으로 백엔드 api 요청을 통해 불러와서 프론트상에서는 데이터 가공을 아예 불가능하게 하는 케이스도 본 적 있어요. (물론 저는 개인적으로 선호하는 방식은 아닙니다)

결과적으로 상수화해서 사용하는건 코드가 오히려 조금 늘어나더라도 지향하는게 좋지 않을까? 라는 개인적인 의견입니다. 현재 코드 변경점들은 전 좋은 거 같아요

2024-08-23 11:19 UTC, jisong3377 approved these changes

2024-08-23 12:07 UTC, detourguru approved these changes

2024-08-25 06:34 UTC, sikkzz approved these changes

2024-08-26 04:10 UTC, merged