51 front task feat onboarding db connection
Meetie-One/Meetie-front pull request #58
Opened 2024-08-23 05:05 UTC by ejinn1

- [[GITHUB ISSUE LINK]()]

## 💡 변경사항 & 이슈
온보딩 정보입력 supabase db와 연동
<br>

## ✍️ 관련 설명
타이틀에 들어가는 이름과 프로필에 들어가는 이름을 로그인된 해당 유저 이름으로 변경
post, get 요청 핸들러 추가, 핸들러에 supabase db 연결해서 정보 입력, 검색 추가

`onboarding` 테이블
| id  | user_id | position | purposes | styles | period |
| --- | ------- | -------- | -------- | ------ | ------ |

supabase에는 array타입이 없는거같아서 일단 텍스트로 넣어놨습니다. (purposes, styles)
더 찾아보고 array타입으로 변경할 예정입니다.

현재 이름 불러오는거랑 데이터 가져오는 부분에서 로딩시간이 좀 걸리는데 어떤 방식으로 해결할지 잘 모르겠습니다
서버 컴포넌트로 변경해보려다가 잘되지않아서 일단은 클라이언트 컴포넌트로 해두었습니다.

로딩 컴포넌트는 추후에 추가할 예정입니다.

- 현재 job으로 되어있는 부분은 다음 브랜치에서 position으로 변경할 예정입니다.
<br>

## ⭐️ Review point
테스트 해보고 이상한 부분 있으면 말해주세요
<br>

## 📷 Demo

https://github.com/user-attachments/assets/ee182809-799c-4f53-92d8-de80236683c4

<br>

2024-08-23 07:02 UTC, soyoung125 commented
[supabase 배열 컬럼 만들기](https://supabase.com/docs/guides/database/arrays?queryGroups=database-method&database-method=dashboard&queryGroups=language&language=js#create-a-table-with-an-array-column)
아직 코드 다 읽어보진 않았지만 저번에 string array 사용하는 방법을 읽은 기억이 나서 공유해드립니다!
type을 text로 하고 define as array 선택하시면 될 것 같아요.

2024-08-23 10:28 UTC, sikkzz requested changes

2024-08-23 10:28 UTC, sikkzz commented on next.config.mjs
<img width="366" alt="스크린샷 2024-08-23 오후 7 18 19" src="https://github.com/user-attachments/assets/15b452cc-6338-4b86-b0a6-a57422c60bab">

저는 이미지 에러가 아직 뜨는데 저만 뜨나요? 저만 뜨는거라면 뭐 프로필 이미지 동의 이런 부분에서 걸리는게 있는건가.. 싶기도 하고

2024-08-23 10:28 UTC, sikkzz commented on src/app/api/onboarding/route.ts
> +interface postDataTypes {
PascalCase

2024-08-23 10:28 UTC, sikkzz commented on src/app/api/onboarding/route.ts
> +    console.log(data);
테스트가 끝난 콘솔이라면 지우셔도 될 거 같아요

2024-08-23 10:28 UTC, sikkzz commented on src/app/onboarding/complete/page.tsx
> +  }, []);
여기는 결국 전체적으로 리팩토링이 필요하겠네요

인지하고 계실거라 생각하니까 따로 코멘트는 안달고 todo만 적어주세용

2024-08-23 10:28 UTC, sikkzz commented on src/app/onboarding/complete/page.tsx
> +                  <div className="absolute w-[80px] h-[80px] bg-[#0017E2] mix-blend-hue z-10" />
이렇게 로직 처리가 추가되니까 결국은 data fetching 라이브러리가 강점을 보이지 않을까 싶네요

react-query -> useQuery로 조회
react suspense를 사용해서 로딩 UI 제공
useSuspenseQuery 사용해서 페이지에서 전체 데이터 조회가 완료되지 않을 경우 사용자에게는 loading UI를 제공하고 모든 데이터 조회 완료시 페이지 사용자에게 제공
react-error-boundary를 사용해 error fallback UI 제공

해당 내용은 사실 이렇게 말씀드린다고 직관적으로 이해하기 어려우시겠지만 서칭 조금 해보시고 이후에 제가 코드와 함께 자세하게 설명드려보도록 할게요

물론 위 모든내용들은 react SPA 기준으로 말씀드리는거라 next SSR에선 다를 수 있습니다.

2024-08-23 10:28 UTC, sikkzz commented on src/app/onboarding/complete/page.tsx
> +                  <div className="absolute w-[80px] h-[80px] bg-[#0017E2] mix-blend-hue z-10" />
https://velog.io/@sik02/React-Error-Boundary%EB%A1%9C-Fallback-UI-%EA%B5%AC%EC%84%B1-%EB%B0%8F-%EC%97%90%EB%9F%AC-%EC%B2%98%EB%A6%AC-%EA%B0%9C%EC%84%A0-with-react-query

제 블로그 관련 포스팅인데 읽어보셔도 좋을 거 같아요. 다만 기본 개념에 이해가 어려우시다면 관련 내용 먼저 보시고 읽어보시는걸 추천드립니다~

2024-08-24 07:00 UTC, ejinn1 commented on next.config.mjs
next.config.mjs에 카카오 이미지 가능하도록 수정했슴다

2024-08-24 10:32 UTC, sikkzz commented on next.config.mjs
<img width="339" alt="스크린샷 2024-08-24 오후 7 32 15" src="https://github.com/user-attachments/assets/b8091de0-4730-4751-95c2-91a6b632ed96">

구글 이미지도 추가 부탁드려요~

2024-08-25 05:04 UTC, ejinn1 commented on src/app/onboarding/complete/page.tsx
> +                  <div className="absolute w-[80px] h-[80px] bg-[#0017E2] mix-blend-hue z-10" />
<img width="540" alt="image" src="https://github.com/user-attachments/assets/9b5b4320-2996-42a5-b479-d07050ef9d73">

https://www.youtube.com/watch?v=FvRtoViujGg&t=519s
이 영상에 나오는 부분인데 이런 느낌으로 이해하면 되는걸까요??

2024-08-25 05:07 UTC, ejinn1 commented on next.config.mjs
추가했습니당

2024-08-25 06:04 UTC, sikkzz commented on src/app/onboarding/complete/page.tsx
> +                  <div className="absolute w-[80px] h-[80px] bg-[#0017E2] mix-blend-hue z-10" />
네 맞아요 Foobar 컴포넌트에서 api 요청이 완료될때까지 <Loader /> 렌더링, api 에러 발생 시 <MyErrorPage /> 렌더링, 모두 정상 작동 완료하면 Foobar 렌더링 이렇게 이루어집니다

2024-08-25 09:14 UTC, soyoung125 approved these changes

2024-08-26 00:59 UTC, ejinn1 commented on src/app/onboarding/complete/page.tsx
> +                  <div className="absolute w-[80px] h-[80px] bg-[#0017E2] mix-blend-hue z-10" />
넹

2024-08-26 03:51 UTC, detourguru approved these changes

2024-08-26 04:18 UTC, sikkzz approved these changes

2024-08-26 04:20 UTC, jisong3377 approved these changes

2024-08-26 04:20 UTC, merged