63 front task refactor onboarding data api handler
Meetie-One/Meetie-front pull request #68
Opened 2024-08-27 09:35 UTC by ejinn1

- https://github.com/Meetie-One/Meetie-front/issues/63

## 💡 변경사항 & 이슈
온보딩 데이터, api 리펙토링, 라우팅 설정
<br>

## ✍️ 관련 설명
온보딩 데이터를 하나의 객체로 관리하도록 변경했습니다.
step 컴포넌트로 넘기는 prop의 type을 하나로 통일했습니다.

온보딩 post, get api를 `react-query`와 `axios`를 사용하는 방식으로 변경했습니다.
온보딩 완료 페이지에서 프로필을 컴포넌트로 분리시켰습니다. (재사용을 고려하지 않고 만들어서 재사용을 한다면 수정해야될거같습니다.)

로그인을 했을 때 redirect 페이지에서 온보딩을 완료했는지를 확인하고 완료했으면 스터디 `/study-list`로 라우팅, 아니면 `/walk-whrough`로 라우팅 시키도록 했습니다.

<br>

## ⭐️ Review point
skip 버튼이 있어서 온보딩 과정을 필수로 해야될지 정해야할거같습니다.
로딩처리 부분이 아직 매끄럽지 않아서 추가로 변경해야될거같습니다.
<br>

## 📷 Demo

<br>

2024-08-27 16:23 UTC, sikkzz requested changes

2024-08-27 16:23 UTC, sikkzz commented on src/apis/onboarding/postOnboarding.ts
> +  return axiosInstance.post(END_POINTS.ONBOARDING, JSON.stringify(onboardingForm), config);
JSON.stringify 지워도 제대로 동작하지않나요?

2024-08-27 16:23 UTC, sikkzz commented on src/apis/onboarding/postOnboarding.ts
> +import { axiosInstance } from "../axiosInstance";
절대경로

2024-08-27 16:23 UTC, sikkzz commented on src/apis/userInfo/getUserInfo.ts
> +  console.log(user);
콘솔 제거

2024-08-27 16:23 UTC, sikkzz commented on src/apis/userInfo/getUserInfo.ts
> +import { axiosInstance } from "../axiosInstance";
절대경로

2024-08-27 16:23 UTC, sikkzz commented on src/apis/userInfo/getUserInfo.ts
> +  const { data } = await axiosInstance.get(`${END_POINTS.USER_INFO}?user_id=${user.data.user?.id}`);
<img width="542" alt="스크린샷 2024-08-28 오전 1 06 14" src="https://github.com/user-attachments/assets/fea3c041-c49c-4699-b562-796b04b2d508">
<img width="524" alt="스크린샷 2024-08-28 오전 1 06 11" src="https://github.com/user-attachments/assets/1196101a-a573-4ceb-8860-f7315501e20f">

사진처럼 작성을 권장드려요

1. 상수처리된 end_point는 그 변수 그대로 가져와 사용하는게 상수 처리에 의미가 있다고 생각해요
2. 옵셔널 체이닝(?.)은 원래 사용을 최대한 지양해야합니다. 데이터가 있든 없든 디버깅 에러를 발생시키지 않기에 원하는 의도대로 동작시키려면 제대로된 조건부 처리를 달아주는게 좋다고 생각해요

2024-08-27 16:23 UTC, sikkzz commented on src/app/onboarding/complete/page.tsx
> +        </Suspense>
suspense가 여기있는김에 useUserInformationQuery도 OnboardingProfile 내부에서 돌려주는게 좋을 거 같네요

그래야 useSuspenseQuery 사용하고 그 로딩처리가 저기 suspense로 처리될 거 같아요. onBoardingTitle에도 데이터가 쓰이니까 컴포넌트로 article 내부 자체를 한번 더 묶어줘야 겠네요.

그럼 여기 page 자체도 "use client" 제거도 가능할 거 같구요

2024-08-27 16:23 UTC, sikkzz commented on src/app/onboarding/complete/page.tsx
무엇보다 지금 저는 이미지가 제대로 안뜨네요. 콘솔창에도 이미지가 없다고 에러를 뱉고 있네요

<img width="355" alt="스크린샷 2024-08-28 오전 1 14 03" src="https://github.com/user-attachments/assets/df3c128e-dcf0-4953-a75c-f47d4839f107">

2024-08-27 16:23 UTC, sikkzz commented on src/app/api/user-info/route.ts
<img width="560" alt="스크린샷 2024-08-28 오전 1 16 20" src="https://github.com/user-attachments/assets/a79ffc2a-659c-46f4-8bd5-e2f0d0b564fa">

변경 추천 드려요. 이후에 data 가져다 쓸 때 data[0] 을 안붙여도 된다는 장점이 있습니다.

2024-08-27 16:23 UTC, sikkzz commented on src/app/onboarding/page.tsx
여기도 컴포넌트로 쿼리는 내부로 넣어주는게 좋겠네용

2024-08-27 16:23 UTC, sikkzz commented on src/app/user/[id]/page.tsx
여긴 소영님이 보고 수정하시겠지만 동일하게 컴포넌트 내부에서 query 돌려야하는데

주석처리를 달아주시거나 아님 관련 코드 없애놓고 구두 전달하거나 알려드리는게 나을 거 같네요

2024-08-27 16:23 UTC, sikkzz commented on src/hooks/api/userInfo/useUserInformationQuery.ts
여기도 useOnboardingCompleteQuery형식이랑 동일하게 바꾸면 될 거 같네요

suspenseQuery 사용, 타입 명시를 통한 자동 완성 추가

2024-08-27 16:24 UTC, sikkzz commented
suspense 관련 처리랑 react-query 사용 관련은 어쩌면 이후에 변경될 수도 있겠지만 우선은 리뷰대로 수정 부탁드려요

그리고 추후 수정되더라도 제가 달아드리는 리뷰 내용들이 react에서는 흔히 사용되는 로직과 구성인걸 알아두시면 좋을 거 같아요~

2024-08-28 01:29 UTC, soyoung125 approved these changes

2024-08-28 01:29 UTC, soyoung125 commented on src/apis/userInfo/getUserInfo.ts
> +import { axiosInstance } from "../axiosInstance";
userInfo 관련 코드는 제 코드를 가져오신거라 제가 수정하겠습니다!

2024-08-28 01:29 UTC, soyoung125 commented on src/app/api/user-info/route.ts
```
const { data } = await supabase.from("userinfo").select().eq("id", params.id).single()
```
single을 사용하면 [0]을 안붙여도 되더라구요. 그래서 single로 수정해놓은 상태입니다!

2024-08-28 01:29 UTC, soyoung125 commented on src/app/onboarding/complete/page.tsx
제가 스키마 변경시켜서 그렇습니다. 카멜케이스 써주세요!

2024-08-28 01:29 UTC, soyoung125 commented on src/app/onboarding/complete/page.tsx
> +  const profileImage = userData && userData.data[0].profile_image;
여기 profileImage

2024-08-28 01:29 UTC, soyoung125 commented on src/app/user/[id]/page.tsx
넵

2024-08-28 01:29 UTC, soyoung125 commented on src/hooks/api/userInfo/useUserInformationQuery.ts
넵

2024-08-28 01:31 UTC, jisong3377 commented on src/hooks/onboarding/useOnboardingForm.ts
> +import { usePostOnboardingMutation } from "../api/onboarding/usePostOnboardingMutation";
여기도 경로요 !!

2024-08-28 05:00 UTC, ejinn1 commented on src/apis/onboarding/postOnboarding.ts
> +  return axiosInstance.post(END_POINTS.ONBOARDING, JSON.stringify(onboardingForm), config);
그러네염

2024-08-28 06:26 UTC, ejinn1 commented on src/app/onboarding/complete/page.tsx
노션에 DB 정리해서 올려놓겠습니다 변경됐을 때 확인이 안되서 바로 수정하기가 어렵네여

2024-08-28 06:26 UTC, ejinn1 commented on src/app/api/user-info/route.ts
온보딩쪽에도 single로 수정하겠슴니다

2024-08-28 06:26 UTC, ejinn1 commented on src/app/onboarding/complete/page.tsx
> +        </Suspense>
complete 전체를 컴포넌트로 분리시켜서 로딩처리를 suspense로 한번에 처리했습니다 소영님 user쪽 변경되면 리베이스해서 한번 더 확인해볼게요

2024-08-28 06:26 UTC, ejinn1 commented on src/app/onboarding/page.tsx
그럼 이 부분은 title에만 userName이 들어가서 이부분만 따로 컴포넌트로 분리 시켰습니당

2024-08-29 01:32 UTC, detourguru approved these changes

2024-08-30 04:02 UTC, sikkzz requested changes

2024-08-30 04:02 UTC, sikkzz commented on src/app/api/onboarding/route.ts
> +      return NextResponse.json({ message: "ok", status: 200, data: data });
NextResponse.json({ message: "ok", status: 200, data });

이렇게 쓰면 됩니다. data 네임과 field명이 같다면 따로 data값을 안넣어줘도 자동으로 들어가요

2024-08-30 04:02 UTC, sikkzz commented on src/app/api/user-info/[id]/route.ts
> +    console.log(data);
제거해도 될 거 같네요

2024-08-30 04:02 UTC, sikkzz commented on src/components/OnBoarding/CompleteBox/CompleteBox.tsx
> +    </article>
상위 onboarding/complete page쪽으로 article과 Link까지는 뺴는게 좋지 않을까요? 결국 query의 data가 필요한건 OnboardingTitle과 OnboardingProfile만 필요하니까 얘네만 남겨두는 방식으로요

2024-08-30 04:02 UTC, sikkzz commented on src/app/user/[id]/page.tsx
> +"use client";
제거해주세요 이건 rebase 할 때 잘 못 들어간거 같네용

2024-08-30 04:25 UTC, jisong3377 approved these changes

2024-08-30 05:32 UTC, sikkzz approved these changes

2024-08-30 05:37 UTC, merged