55 front task studyroom list page feat 1
Meetie-One/Meetie-front pull request #71
Opened 2024-08-27 12:36 UTC by detourguru

- [GITHUB ISSUE LINK]()

## 💡 변경사항 & 이슈
- 도움말 hover 추가
- 페이지 카운트 컴포넌트 기능 구현
- 모집중만 조회하는 필터링 기능 구현
<br>

## ✍️ 관련 설명
studyRoom-list 페이지의 기능 구현 (1)
<br>

## ⭐️ Review point
페이지 카운트 시 total은 전체 스터디 카드로 하면 될 것 같은데 current 집계 기준이 좀 애매합니다
밑으로 쭉 스크롤 하는건지 아니면 카드처럼 옆으로 넘기는건지 피그마상으로는 명확하지 않아서
의견 있으신분 의견 부탁드립니다

지금은 임시로 total = current입니다
<br>

## 📷 Demo

<br>

2024-08-28 02:37 UTC, ejinn1 requested changes
StudyCard, StudyList 컴포넌트가 준식님 변경점이랑 겹치는게 있는데 확인헤봐야할거같습니다

2024-08-28 02:37 UTC, ejinn1 commented on src/components/Study/StudyCard.tsx
> +  const filtered = studyListData?.data.filter((data) => data.id == id)[0];
filter대신 find함수 쓰면 [0] 안붙혀도 되요

2024-08-28 02:37 UTC, ejinn1 commented on src/components/Study/StudyList/StudyList.tsx
> +  };
handleStudyCardList 이 부분은 함수로 따로 안빼도 아래 return문 안에그대로 작성가능해요
handlePageCounter 이 부분도 html부분을 아래 return문 안에 작성하고 total, current 부분을 따로 구하는게 나을거같습니다

```js
<article className="mx-4 pb-[80px]">
  <h1 className="text-bold-18 mb-5">
    지금 떠오르고 있는
    <br />
    스터디룸
  </h1>
  <div className="flex justify-between mb-[27px]">
    <CheckBox checked={isChecked} onChange={handleCheckboxChange}>
      모집중만 보기
    </CheckBox>
    <PageConter current={current} total={total} />;
  </div>
  {filteredStudy?.map((data) => <StudyCard key={data.id} id={data.id} />)}
</article>
```

2024-08-28 02:55 UTC, soyoung125 approved these changes

2024-08-28 02:55 UTC, soyoung125 commented on src/components/Study/StudyCard.tsx
> +    <>
fragment <></> 제거해도 될 것 같습니다.

2024-08-28 03:03 UTC, soyoung125 commented
제 생각엔 피그마에 stepper 같은 게 있어서 카드를 넘기는 방식으로 설계를 한 것으로 보입니다!
![image](https://github.com/user-attachments/assets/dfa7345e-1091-4c96-a2e2-bd5ec16e6c3b)

근데 구현에 시간이 많이 걸릴 것 같다면 스크롤로 해도 괜찮을 것 같아요.

2024-08-28 04:25 UTC, sikkzz requested changes
<img width="540" alt="스크린샷 2024-08-28 오후 1 22 01" src="https://github.com/user-attachments/assets/2fcd26b5-44b7-48d1-a3c6-ee1075378ce5">
<img width="472" alt="스크린샷 2024-08-28 오후 1 21 57" src="https://github.com/user-attachments/assets/4db72844-1f0e-4f04-a2d7-8da6da6fd996">
<img width="551" alt="스크린샷 2024-08-28 오후 1 21 55" src="https://github.com/user-attachments/assets/4f707414-570c-4dd2-9f75-e385631b3dfc">

에러들이 잔뜩 떠있는데 그냥 pr을 올린건 이해가 가지 않네요. 추가적으로 미완성된 코드는 PR을 올리는게 아닙니다. 저는 현재 이 코드들이 전체적으로 미완성으로 보이네요

작성자가 완벽히 구성하고 테스트까지 마친 코드도 리뷰를 진행해도 코드량이 늘어나는데 미완성된 코드를 PR을 올리면 리뷰자가 뭐가 문제인지 기능 테스트도 해봐야하고 더불어 코드도 파악하면서 리뷰를 달아야합니다.

그럼 리뷰량 늘어나는건 당연하고 수정이 늘어나니까 순수 코드량도 계속 늘어나게 되겠죠. 악순환의 반복입니다. 앞으로 미완성된 PR은 작성하지 말아주세요. 미구현된 사유가 있다면 PR 내용에 작성해주셔야 합니다. 그러라고 있는게 ISSUE고 PR입니다.

추가적으로 해당 브랜치도 제꺼 65번 이후로 리베이스하고 더 수정 부탁드려요

2024-08-28 04:25 UTC, sikkzz commented on src/app/study-room/list/page.tsx
<img width="439" alt="스크린샷 2024-08-28 오후 1 06 13" src="https://github.com/user-attachments/assets/26268cb6-8f07-4c28-8a60-b487ceb2d77c">

tooltip 컴포넌트때문에 외곽선 생기네요.

추가적으로 Header.RightButton을 내부 컴포넌트로 두면 compound 패턴으로 header를 구성한 의미가 없습니다. 내부 children으로 두는게 아닌 외부로 빼서 사용하고 on/off 여부에 따라 보여주는 식으로 표시하는게 좋아보입니다. 또한 이후 재사용 여부가 없기 때문에 message props도 받을 이유가 없고 그냥 static한 컴포넌트로 구성하시면 됩니다.

다른데 사용되는 곳이 있다면 말씀해주세요

2024-08-28 04:25 UTC, sikkzz commented on src/components/Study/CheckBox.tsx
기능구현인데 현재 이 상태는 체크 상태 여부만 바꿔주는거 아닐까요? 체크 여부에 따라 조건부 렌더링도 바뀌어야하고 그거에 맞춰서 checked 여부랑 handle 함수가 작성되어야 하며 이후 api 연결 까지 고려해서 작성을 해야하는데 이건 기능이 구현된게 아니라고 생각해요

2024-08-28 04:25 UTC, sikkzz commented on src/components/Study/CheckBox.tsx
>            name=""
name값이 비어있을꺼면 필드가 필요 없겠네요

2024-08-28 04:25 UTC, sikkzz commented on src/components/Study/CheckBox.tsx
>      <>
제거

2024-08-28 04:25 UTC, sikkzz commented on src/components/Study/StudyList/StudyList.tsx
> +  };
의진님이 예시는 달아주셨지만 이런식으로 코드작성하는건 안됩니다

한 컴포넌트에서는 return문으로 특정된 하나의 UI만 렌더링하는게 좋습니다. 여러개를 조건부로 return시 컴포넌트 자체의 의미가 퇴색되며 여러 기능을 하는 코드로 변해버립니다. react의 장점을 그냥 버리는거나 마찬가지에요. 레거시 코드로 가기 딱 좋은 케이스의 코드입니다.

조건부 렌더링, 조건부 작성중에서도 역할이 애매하거나 작성이 모호하면 컴포넌트 설계를 다시해보고 재사용성 고려하면서 컴포넌트를 설계하고 구성해야합니다.

이런 고민이 필요하기 때문에 설계가 중요하고 어렵다고 하는거지 그냥 고민 없이 작성하고 돌아가는 코드는 정상 동작해도 아무 의미가 없습니다.

2024-08-28 04:27 UTC, sikkzz requested changes

2024-08-28 04:27 UTC, sikkzz commented on src/components/Study/StudyList/StudyList.tsx
>  import PageConter from "@/components/Study/PageCounter";
피그마상 디자인에서는 페이징으로 나와있지만 인피니티 스크롤이 더 기획상 맞아보입니다.

현재 피그마 디자인으로 보면 페이징의 기획도 어색하고 말씀하신대로 페이지 카운팅도 어려움이 있어보입니다. 모바일 기능 특성상 무한 스크롤이 훨씬 편리하기 때문에 페이징 UI 및 기능은 없어도 될 거 같아 보이네요

2024-08-29 07:17 UTC, sikkzz requested changes

2024-08-29 07:17 UTC, sikkzz commented on src/components/Study/StudyCard.tsx
이거 moment 왜 설치하신걸까요? 이미 관련 라이브러리로 date-fns를 쓰고 있습니다. 서로 호환안되거나 구현 불가능한 기능은 없을텐데 date-fns로 사용해주세요

2024-08-29 07:17 UTC, sikkzz commented on src/types/study.ts
현재 많은곳에서 공통으로 사용하고 있는 타입입니다. 이런 파일들을 고려도 없이 막 변경하시면 곤란합니다. 제가 설계한 타입이고 null 처리가 필요해서 처리해놓은 상태입니다. 변경하신 부분 때문에 현재 바로 에러 발생하고 있습니다. 

혼자 사용하는 파일이 아닌 공통으로 사용하는 파일을 수정할때는 사용되는 곳을 모두 고려하고 바꾸셔야하는데 그냥 막 바꾸신거 같네요 롤백 부탁드려요

<img width="1290" alt="스크린샷 2024-08-29 오후 4 15 55" src="https://github.com/user-attachments/assets/da0ce30b-5cdd-4fd3-8cb1-e2b5cbd7d530">

2024-08-29 07:24 UTC, detourguru commented on src/types/study.ts
헉 넵 롤백할게여 제 브랜치에서만 변경 일어나는 줄 알았어여

2024-08-30 04:25 UTC, jisong3377 approved these changes

2024-09-01 05:19 UTC, ejinn1 approved these changes

2024-09-03 05:43 UTC, sikkzz requested changes

2024-09-03 05:43 UTC, sikkzz commented on src/components/Study/CheckBox.tsx
> +interface checkboxProps extends PropsWithChildren {
CheckBoxProps

2024-09-03 05:43 UTC, sikkzz commented on src/components/Study/Explorer/ExplorerTab.tsx
> +              <PageConter total={6} />
말씀드린대로 PageCounter는 미사용될 컴포넌트인데 삭제하시면 되지 않을까요?

2024-09-03 05:43 UTC, sikkzz commented on src/components/Study/Explorer/ExplorerTab.tsx
>                <CheckBox>모집중만 보기</CheckBox>
에러납니다

2024-09-03 05:43 UTC, sikkzz commented on src/components/Study/StudyList/StudyList.tsx
> +  }, [checked]);
이렇게 필터링을 할게 아니라 필터링된 리스트를 조회하는 api를 하나 만들거나 현재 존재하는 studyList 조회 api에 필터 옵션을 넣어야 합니다.

저렇게 state로 관리해버리면 state로 필터링을 변경해도 studyList가 업데이트 되는걸 같이 감지하지 못합니다. 캐싱 또한 활용이 불가능하죠

2024-09-04 03:13 UTC, detourguru commented on src/components/Study/Explorer/ExplorerTab.tsx
> +              <PageConter total={6} />
이거 총 페이지수는 표시 되어야하지 않을까 싶어서 냅뒀습니다 explorer에서도 동일한 컴포넌트로 사용중입니닷

2024-09-04 08:43 UTC, sikkzz requested changes

2024-09-04 08:43 UTC, sikkzz commented on src/components/Study/Explorer/ExplorerTab.tsx
> +              <PageConter total={6} />
무한 스크롤 기능에서 총 페이지수 어떻게 존재할 수 있나요? 무한스크롤 방식 서칭해보시기 바랍니다

탐색 페이지, 리스트 페이지 모두 무한스크롤 방식으로 말씀드린부분입니다

2024-09-05 00:26 UTC, detourguru commented on src/components/Study/Explorer/ExplorerTab.tsx
> +              <PageConter total={6} />
넵 무한스크롤 방식인건 이해했는데 그래도 총 카드 수는 필요하지 않을까요?

2024-09-05 03:30 UTC, sikkzz commented on src/components/Study/Explorer/ExplorerTab.tsx
> +              <PageConter total={6} />
피그마 기획상 총 카드수가 아닌 페이지 단위로 기획한거 같아요. 근데 게시물이 많을 예정이고 그걸 고려해서 무한 스크롤이 더 나은 방향인데 예를들어 100개 200개의 스터디 게시물이 있다면 오히려 total이 number로 보이는건 UI상 안 예쁠거 같아요. 사용자 입장에서 필요하지도 않구요

어떻게 생각하시나요?

2024-09-05 04:58 UTC, detourguru commented on src/components/Study/Explorer/ExplorerTab.tsx
> +              <PageConter total={6} />
페이지네이션 삭제 (무한스크롤 or top N)

2024-09-05 10:03 UTC, sikkzz requested changes

2024-09-05 10:03 UTC, sikkzz commented on src/app/study-room/list/page.tsx
> +                  height={81}
70으로 변경 부탁드려요

2024-09-05 10:03 UTC, sikkzz commented on src/app/study-room/list/page.tsx
> +                  height={81}
priority props도 추가해주세요 두 내용 다 console warning 관련해서입니다

2024-09-05 10:03 UTC, sikkzz commented on src/components/Study/StudyList/StudyList.tsx
> +  }, [checked, isLoading]);
isLoading은 deps에서 빠져도 되는거 아닌가요

2024-09-05 10:03 UTC, sikkzz commented on src/components/Study/StudyList/StudyList.tsx
> +    setChecked(!checked);
setChecked((prev) => !prev) 가 더 정확하긴 합니다. prev 네이밍은 맞춰서 지어주면 됩니다

2024-09-05 10:03 UTC, sikkzz commented on src/components/Study/StudyList/StudyList.tsx
> +  const { data, refetch, isLoading } = useStudyListQuery(queryString);
이거 queryString 변동이 없는거면 그냥 고정으로 두는건 어떠세요?

2024-09-05 10:03 UTC, sikkzz commented on src/components/Study/StudyList/StudyList.tsx
> +      {data.data &&
data.data && 없으면 에러가 있나요?

2024-09-05 10:03 UTC, sikkzz commented on src/components/Study/StudyRoomList/StudyCard.tsx
> +  };
이거 저도 사용할 예정이라 util로 제 브랜치에 빼놨는데 todo로만 적어주세요 이후에 적용하면 될 거 같아요

2024-09-05 10:03 UTC, sikkzz commented on src/hooks/api/study/useStudyListQuery.ts
> +    );
querystring의 변동이 없다면 여기도 고정으로 변경할 수 있을 거 같아서요

2024-09-06 01:28 UTC, detourguru commented on src/hooks/api/study/useStudyListQuery.ts
> +    );
이거 다른 페이지에서도 쿼리스트링 쓸거라 받아와서 사용할 수 있도록 작업했습니다!

2024-09-06 01:29 UTC, detourguru commented on src/components/Study/StudyList/StudyList.tsx
> +      {data.data &&
조회해온 데이터가 없어서 null일 경우가 있어서 (필터링 걸었을때 등) 예외처리 해뒀습니다

2024-09-06 01:29 UTC, detourguru commented on src/components/Study/StudyList/StudyList.tsx
> +  }, [checked, isLoading]);
오 맞습니다 이거 뭐 테스트하다가 남겨뒀네요 지울게여

2024-09-06 01:37 UTC, detourguru commented on src/components/Study/StudyList/StudyList.tsx
> +  const { data, refetch, isLoading } = useStudyListQuery(queryString);
필터링 쪽 때문에 또 사용할 수 있을 것 같아서 이렇게 작업했습니다!

2024-09-06 09:24 UTC, sikkzz commented on src/components/Study/StudyList/StudyList.tsx
> +      {data.data &&
null일 경우의 UI를 하나 만드는게 좋을 거 같아요. 그리고 data가 없을때 예외처리 UI를 아니면 원래 UI 렌더링 하는 식으로요!

주석으로 todo만 달아주세요~

2024-09-06 09:24 UTC, sikkzz approved these changes

2024-09-06 09:26 UTC, merged