62 front task create a edit profile api handler
Meetie-One/Meetie-front pull request #72
Opened 2024-08-27 16:49 UTC by soyoung125

- https://github.com/Meetie-One/Meetie-front/issues/62

## 💡 변경사항 & 이슈
userinfo 데이터 GET, PATCH api 제작
<br>

## ✍️ 관련 설명
마이페이지와 프로필, 프로필 수정 페이지에 userinfo 데이터를 연동했습니다.

마이 페이지에서는 auth 데이터를 가지고 userinfo에서 데이터를 불러와야 하고, 프로필 페이지에서는 userinfo 테이블의 id로 데이터를 불러와야 한다고 생각해서 각각 `user-info?user_id=`와 `user-info/id`로 구분했습니다.
코드를 최대한 재활용하고 싶어서 `useUserInformationQuery` 훅에 매개변수 전달 여부로 두 api를 구분해서 호출하게 했습니다.

유저 데이터를 수정할 수 있도록 patch api `user-info/id`를 제작했습니다.
지난 이슈에서 제작한 이벤트 핸들러를 활용해서 이름, 자기소개, 대표뱃지, 스터디 태그, 프로필 이미지를 업데이트할 수 있도록 했습니다.
또한, 개인정보 제공 동의 on/off도 업데이트를 적용했는데 생각보다 api 호출 시간이 길게 느껴져서 이 부분은 방법을 찾아봐야 할 것 같습니다.
<br>

## ⭐️ Review point
로그인 후 유저 데이터 수정이 정상적으로 되는지 확인 부탁드립니다.

마이페이지 --공개용 프로필--> 프로필 페이지 --수정--> 프로필 수정 페이지 --완료--> 프로필 페이지
마이페이지 --회원정보 수정--> 프로필 수정 페이지 --완료--> 프로필 페이지

위와 같은 프로우에서 화면 이동이 정상적으로 동작하는지 확인 부탁드립니다.

로그인하지 않고 페이지에 접근을 방지할 수 있는 기능이 필요할 것 같습니다.
<br>

## 📷 Demo
![image](https://github.com/user-attachments/assets/1aeb1e9e-9003-4f71-b5b9-1a96a6875642)

<br>

2024-08-28 04:35 UTC, sikkzz requested changes
의진님 리뷰에 달아드린거랑 겹치는 내용들이 많아서 그부분들은 전체적으로 신경써서 한번 확인 부탁드릴게요~

2024-08-28 04:35 UTC, sikkzz commented on src/apis/userInfo/updateUserInfo.ts
> +}) => {
interface로 빼서 작성 부탁드려요. 컨벤션으로 정하기도 했고 내부에 넣어놓으면 코드 파악에 복잡도가 미미하게 생깁니다

2024-08-28 04:35 UTC, sikkzz commented on src/apis/userInfo/updateUserInfo.ts
> +  return axiosInstance.patch(url, updateUserForm, config);
의진님 리뷰에도 달아드렸는데 end_point 상수 자체를 가져다 쓰는게 제일 이상적인거 같아요. 의진님 리뷰 내용 한번 확인해주세요

2024-08-28 04:35 UTC, sikkzz commented on src/apis/userInfo/getUserInfo.ts
> +    params = `?user_id=${user.data.user?.id}`;
옵셔널 체이닝 대신 정확한 조건을 달아주면 제거가 가능합니다.

옵셔널 체이닝의 사용 지양 이유 또한 의진님 리뷰에 달아놓았습니다

2024-08-28 04:35 UTC, sikkzz commented on src/app/mypage/page.tsx
> +          <Avatar src={user?.profileImage ?? "/svg/ic-user.svg"} />
여기 옵셔널 제거는 suspenseQuery를 통해 제거 가능해요. 마찬가지로 내부로 컴포넌트 하나 생성해서 query문 달아줘야하구요

2024-08-28 04:58 UTC, ejinn1 commented on src/hooks/api/userInfo/useUserInformationQuery.ts
> +};
useSuspenseQuery로 변경하면 옵셔널안써도 에러 안나요

```js
  const { data: userData } = useSuspenseQuery<GetUserInfoResponseType, AxiosError>({
    queryKey: [QUERY_KEYS.USER_INFO],
    queryFn: () => getUserInfo(id),
  });

  const user = userData.data;
```

이후에 로딩관련 처리도 하면 좋을거같습니당

2024-08-28 09:43 UTC, ejinn1 approved these changes

2024-08-28 10:10 UTC, sikkzz requested changes

2024-08-28 10:10 UTC, sikkzz commented on src/hooks/mypage/useEditProfileForm.ts
> +  id?: number;
이거 undefined type 들어가야할 이유가 있을까요? 없으면 하단에 handleSubmit if문도 필요없을 거 같아서요

2024-08-28 13:52 UTC, soyoung125 commented on src/hooks/mypage/useEditProfileForm.ts
> +  id?: number;
여기 확인을 못했었네요.. 수정했습니다.

2024-08-28 17:35 UTC, sikkzz approved these changes
로그인 안한 상태에서는 페이지 접근이 루트랑 /login, auth-redirect만 접근 가능하게 미들웨어에서 설정해놓았던거 같은데 아닐까요?

뭐 우선 구현이 필요하더라도 이후 브랜치에서 하시면 될 거 같긴합니다만 처리가 되는걸로 기억해서요

2024-08-29 01:33 UTC, detourguru approved these changes

2024-08-29 01:34 UTC, jisong3377 approved these changes

2024-08-29 02:01 UTC, merged