50 front task feat task
Meetie-One/Meetie-front pull request #74
Opened 2024-08-28 05:55 UTC by jisong3377

- [GITHUB ISSUE LINK]()

## 💡 변경사항 & 이슈
과제 인증 화면의 컨텐츠 입력 부분입니다.
3가지(앨범, 카메라, 링크) 중에 앨범 업로드만 구현되었습니다.
<br>

## ✍️ 관련 설명
업로드 방법 중 카메라는 input에 capture 속성을 주면 카메라가 실행된다고 하는데 모바일로 확인하면서 기능을 구현해야 될 것 같습니다.
업로드 방법 중 링크는 디자인이 없어 임의로 모달로 만들어야 할 것 같습니다.
<br>

## ⭐️ Review point
바텀시트인 TaskConfirmSheet에서 업로드 기능을 구현하느라 많이 헤매었는데 코드적으로 더 좋은 방법이 있으면 공유 부탁드립니다.🥹
<br>

## 📷 Demo
https://github.com/user-attachments/assets/222f4cf5-92e8-4039-bf0f-f0c200540ff8
<br>

2024-08-28 09:55 UTC, sikkzz requested changes
이후부터는 PR 작성시 Assignees, Labels 채워주시고 작성할 때 어느 라우팅에서 어떤 기능 테스트해야하는지 자세하게 적어주세요

<img width="328" alt="스크린샷 2024-08-28 오후 6 54 49" src="https://github.com/user-attachments/assets/21c87be4-801f-4731-983a-37621a1263df">

2024-08-28 09:55 UTC, sikkzz commented on src/app/task-confirm/page.tsx
> +import React, { useState } from "react";
React 제거

2024-08-28 09:55 UTC, sikkzz commented on src/components/TaskConfirmSheet/TaskConfirmSheet.tsx
> +      handleImageUpdate(uploadType, null);
실패시 null을 업로드할 이유가 있을까요? 없어도 될 코드 같은데요

여길 바꾸면 handleImageUpdate uploadImage 파라미터 type이 string으로 고정될 거고 미사용 코드들 삭제 가능하겠네요

2024-08-28 09:55 UTC, sikkzz commented on src/components/TaskConfirmSheet/TaskConfirmSheet.tsx
> +  handleImageUpdate: (uploadType: string, uploadImage: string | null) => void;
null 타입 삭제

2024-08-28 09:55 UTC, sikkzz commented on src/components/StudyRoom/TaskConfirmAddItem/TaskConfirmAddItem.tsx
> +  const handleImageUpdate = (uploadType: string, uploadImage: string | null) => {
null 타입 삭제

2024-08-28 09:55 UTC, sikkzz commented on src/components/StudyRoom/TaskConfirmAddItem/TaskConfirmAddItem.tsx
> +    if (uploadImage && addItems.length < 4) {
uploadImage && 삭제

2024-08-28 09:55 UTC, sikkzz commented on src/components/StudyRoom/TaskConfirmArea/TaskConfirmArea.tsx
> +  const handleImageUpdate = (uploadType: string, uploadImage: string | null) => {
uploadImage가 null 타입이 들어갈 필요가 있나요?

2024-08-28 09:55 UTC, sikkzz commented on src/components/StudyRoom/TaskConfirmItem/TaskConfirmItem.tsx
> +      <button className="absolute top-[-7px] right-[-7px] z-50" onClick={onDelete}>
이거 z-index 들어간 이유가 있나요?

2024-08-28 09:55 UTC, sikkzz commented on src/components/TaskConfirmSheet/TaskConfirmSheet.tsx
> +  const handelFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
file을 입력받았을때 그 file이 제대로 로딩된게 아니면 아래 로직은 실행될 필요가 없습니다.

그러니 file의 유무를 함수 맨위에서 걸러줘야겠죠?

2024-08-28 09:55 UTC, sikkzz commented on src/components/TaskConfirmSheet/TaskConfirmSheet.tsx
> +              <input onChange={handelFileChange} type="file" accept="image/*" id="album" hidden />
이미지를 여러장 쓸 예정이라면 multiple 옵션은 왜 사용하지 않는걸까요?

2024-08-28 14:37 UTC, soyoung125 commented on src/components/TaskConfirmSheet/TaskConfirmSheet.tsx
> +        <div className="w-full h-2/5 px-4 py-5 rounded-t-xl bg-[#F9F9F9] z-20">
여기도 z-index 가 필요 없어 보입니다.

2024-08-29 01:28 UTC, ejinn1 approved these changes

2024-08-30 05:47 UTC, soyoung125 approved these changes

2024-09-02 07:34 UTC, sikkzz commented
<img width="361" alt="스크린샷 2024-09-02 오후 4 33 08" src="https://github.com/user-attachments/assets/d8427381-172b-47ff-939c-6347077562d9">
<img width="373" alt="스크린샷 2024-09-02 오후 4 33 11" src="https://github.com/user-attachments/assets/3acf8045-e771-4606-a249-8e2223600cbb">

첫번째 사진 구역에서 여러장 사진 추가 시 두번째 사진 영역에 추가된 사진이 다 들어가야하는거 아닌가요? 근데 한장만 들어가네요

추가적으로 api 및 DB 연결은 왜 안하시는걸까요

2024-09-03 02:56 UTC, detourguru approved these changes

2024-09-03 03:25 UTC, jisong3377 commented
> <img alt="스크린샷 2024-09-02 오후 4 33 08" width="361" src="https://private-user-images.githubusercontent.com/100590110/363598056-d8427381-172b-47ff-939c-6347077562d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMzQwOTEsIm5iZiI6MTcyNTMzMzc5MSwicGF0aCI6Ii8xMDA1OTAxMTAvMzYzNTk4MDU2LWQ4NDI3MzgxLTE3MmItNDdmZi05MzljLTYzNDcwNzc1NjJkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QwMzIzMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODdhMTIzODFmZGQ2ZDYyZGIyZWU2MmI5ZWM5MjQ2ZGUwNDE0MWU2YTg3MjAyYmYzMDczZWY5Y2RiNjRlZWVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GTOSjadqYlXhVlY3T6SJHkrve7YUf3eAfxECDvyP_2M"> <img alt="스크린샷 2024-09-02 오후 4 33 11" width="373" src="https://private-user-images.githubusercontent.com/100590110/363598070-3acf8045-e771-4606-a249-8e2223600cbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMzQwOTEsIm5iZiI6MTcyNTMzMzc5MSwicGF0aCI6Ii8xMDA1OTAxMTAvMzYzNTk4MDcwLTNhY2Y4MDQ1LWU3NzEtNDYwNi1hMjQ5LThlMjIyMzYwMGNiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QwMzIzMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYWEzMTEyZjExMTJlYWFkMjU4MTFjMDg0MmE0ODAzMzE1ODAzNDA5MTg3YzdjMGNkMjlmZTEzNDM4YWRhZmZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.utSIeRoiZxc2w_BArt8tQy1Hpahu0DzuU5lNC9CMUpE">
> 첫번째 사진 구역에서 여러장 사진 추가 시 두번째 사진 영역에 추가된 사진이 다 들어가야하는거 아닌가요? 근데 한장만 들어가네요
> 
> 추가적으로 api 및 DB 연결은 왜 안하시는걸까요

2024-09-03 03:28 UTC, jisong3377 commented
위쪽 인증구역에서 인증에 필요한 내용을 업로드하고 밑에 있는 작은 +버튼은 추가적으로 게시글에 들어가는 내용이라고 생각해서 따로 구현했는데 아닌가요? DB 연동은 작업 중 입니다 !

2024-09-03 05:29 UTC, sikkzz requested changes

2024-09-03 05:29 UTC, sikkzz commented on src/hooks/task/useTaskConfirmForm.ts
> +  };
타입 지정을 정확히 알고 하지 않으면 이런 일이 생깁니다

handleImageUpload 함수 실행 시 files가 없다는건 제대로 동작하지 않았다는 뜻이고 그렇다면 빈 배열이 return이 아니라 아무값도 return 되면 안됩니다.

근데 빈 값 return이 에러가 뜨는 이유는 함수 타입 리턴값을 Promise<string[]>으로 확정지었기 때문입니다. 무조건 string 배열이 리턴되어야 한다고 확정냈으니 에러가 나는거에요. 타입스크립트의 강점이자 단점입니다. 확실히 알고 사용해야 합니다. 2가지 해결법 코드로 남겨드려요

```jsx
  const handleImageUpload = async (files: FileList | null): Promise<string[] | undefined> => {
    if (files) {
      const images = await Promise.all(Array.from(files).map((image) => getBase64(image)));
      return images.filter((image) => image !== "");
    }
    return;
  };
```

```jsx
const handleImageUpload = async (files: FileList | null) => {
    if (!files) {
      return;
    }
    const images = await Promise.all(Array.from(files).map((image) => getBase64(image)));
    
    return images.filter((image) => image !== "");
  };
```

2024-09-03 05:31 UTC, sikkzz commented
> 위쪽 인증구역(싱글 파일 업로드)에서 인증에 필요한 내용을 업로드하고 밑에 있는 작은 +버튼은 추가적으로 게시글에 들어가는 내용(멀티 파일 업로드)이라고 생각해서 따로 구현했습니다 DB 연동은 다음 브랜치에서 하겠습니다

인증 기능은 구현이 불가능할 거 같은데 아닐까요? 그렇다면 인증 구역 이미지를 따로 두는게 아니라 인증 게시글에 대한 미디어를 한번에 다루는게 맞아 보여서요

2024-09-03 05:45 UTC, jisong3377 commented
넵 기획상의 인증 기능은 불가한게 맞고, 저는 인증 구역에 사진이나 링크를 필수적으로 업로드를 해야 인증글이 작성 가능하고, 아래 추가 버튼은 말 그대로 추가로 필수로 업로드를 하지 않아도 되는 것으로 생각했는데 아닐까요?

2024-09-03 05:46 UTC, jisong3377 commented on src/hooks/task/useTaskConfirmForm.ts
> +  };
이부분은 소영님이 작성하신 공통 이미지 업로드 코드로 바뀔 예정입니다 !!

2024-09-04 07:08 UTC, sikkzz approved these changes

2024-09-04 08:23 UTC, merged