77 front task create community board publishing
Meetie-One/Meetie-front pull request #78
Opened 2024-08-29 13:55 UTC by soyoung125

- https://github.com/Meetie-One/Meetie-front/issues/77

## 💡 변경사항 & 이슈
커뮤니티 게시글 작성 페이지 퍼블리싱, 기능 구현
<br>

## ✍️ 관련 설명
커뮤니티 게시글 작성 퍼블리싱 완료
분야 선택, 제목/내용 입력, 이미지 업로드 기능 구현

/community/create -> 에서 확인 가능합니다.

디자인은 스터디 생성 페이지와 과제 인증 페이지의 디자인을 참고했습니다.

DB 연동은 모든 페이지의 퍼블리싱과 기능 구현이 진행된 이후 추가할 예정입니다.
<br>

## ⭐️ Review point
페이지 기능 테스트해보시고 문제가 있다면 말씀 부탁드립니다.
<br>

## 📷 Demo
https://github.com/user-attachments/assets/270b26bb-929a-4a9d-972d-42cde6312c83

<br>

2024-08-30 03:53 UTC, sikkzz requested changes

2024-08-30 03:53 UTC, sikkzz commented on src/app/community/create/page.tsx
하단 버튼 레이아웃에 혹시 사진 같은 경계선이 안보이실까요? 보인다면 해당 레이아웃 bg color는 제거하는게 좋을 거 같아요

여기서 얘기하는 경계선은 border-top 말고 양 옆에 선 같은걸 말씀드리는겁니다. 혹시 저만 보이나 해서요

<img width="422" alt="스크린샷 2024-08-30 오후 12 44 19" src="https://github.com/user-attachments/assets/3cb41583-8ccb-4a73-89ee-2200aa5b3a0c">

2024-08-30 03:53 UTC, sikkzz commented on src/hooks/community/useCreateCommunityPost.ts
> +  const updateProfileForm: CreateCommunityUpdateHandlerType = useCallback((key, value) => {
업데이트 함수 이름은 변경을 해주는게 좋을 거 같네요

2024-08-30 03:53 UTC, sikkzz commented on src/hooks/community/useCreateCommunityPost.ts
> +  };
이미지 업로드 로직만 따로 hook으로 빼는게 좋지 않을까요?

현재까지 확인한 결과 소영님이 맡으신 마이페이지 파트, 여기 커뮤니티 파트, 지예님이 진행중인 과제 인증 파트에서 이미지 업로드 로직이 사용됩니다.

보통 저같은 경우에는 프로젝트에서 사용되는 이미지 업로드 로직은 common hook으로 만들어서 서비스 전체에서 사용하곤 했습니다. multipleImageUpload와 singleImageUpload hook 2개를 따로 만들어서 사용했어요

현재 기능에 문제 없기에 우선시할 작업은 아니지만 고려해보셨으면 좋겠네요. 이미지 업로드 로직이 hook마다 존재할 이유는 사실 없거든요. 여지가 있으시다면 리팩토링 해보시고 문제 있으면 도움 드릴게요

2024-08-30 03:53 UTC, sikkzz commented on src/components/Community/CreatePost/PositionSheet/PositionSheet.tsx
제 파트의 positionSheet와 혼용되는 UI는 제가 나중에 공통화 시켜드리겠습니다. 인지만 해주세요~

2024-08-30 04:23 UTC, jisong3377 approved these changes

2024-08-30 05:07 UTC, soyoung125 commented on src/app/community/create/page.tsx
화면 높이가 810 이하인 디바이스에서는 버튼 레이아웃 밑으로 내용 textarea가 보이는 문제때문에 bg-color를 부여해야 합니다.

Header 컴포넌트 참고해서 px를 제거하고 flex justify-center로 중앙 정렬하니까 외각 선 제거했습니다.

2024-08-30 05:51 UTC, soyoung125 commented on src/hooks/community/useCreateCommunityPost.ts
> +  };
말씀하신대로 useMultiImageUpload와 useSingleImageUpload 제작했는데 고쳐야 할 부분이 있다면 알려주세요!

2024-08-31 06:58 UTC, sikkzz commented on src/app/community/create/page.tsx
이건 우선 해결 방법을 못찾겠네요.. 더 알아볼게요

2024-08-31 07:09 UTC, sikkzz commented on src/hooks/community/useCreateCommunityPost.ts
> +  };
현재는 문제 없는 거 같아요! 추후에 다른 파트에서 사용될 때 문제 없는지 보면 될 거 같고

현재는 base64 방식이지만 img db를 쓰게 되거나 추가적인 기능으로 drag n drop 업로드를 구현한다던지 확장 가능성이 넓으니 그때그때 이 hook들의 리팩토링을 고려하면 될 거 같습니다~

2024-08-31 13:11 UTC, ejinn1 approved these changes

2024-09-01 15:12 UTC, soyoung125 commented on src/app/community/create/page.tsx
Gnb 참고해서 `left-[50%] translate-x-[-50%]`를 추가해줬는데 제가 테스트했을 때에는 선이 사라진 것 처럼 보였습니다.

위치의 차이가 없어서 주가하지 않았었는데 이 차이로 외각 선이 사라지는 이유는 아직 잘 모르겠네요..

2024-09-02 07:22 UTC, sikkzz approved these changes

2024-09-03 02:57 UTC, detourguru approved these changes

2024-09-03 03:20 UTC, merged