81 front task feature email login
Meetie-One/Meetie-front pull request #82
Opened 2024-08-31 14:36 UTC by ejinn1

- https://github.com/Meetie-One/Meetie-front/issues/81

## 💡 변경사항 & 이슈
이메일기반 회원가입, 로그인 기능을 구현했습니다.
<br>

## ✍️ 관련 설명
### `/signup`
회원가입 퍼블리싱 했습니다.
이름, 이메일, 비밀번호, 비밀번호 확인을 입력하면 회원가입과 동시에 로그인되도록 했습니다.

비밀번호 눈 부분은 눈 뜨고있는 아이콘이 없어서 아직 구현하지는 않았습니다.

### `/onboarding/complete`
온보딩을 완료했을 때 로딩 부분을 변경했습니다. 유저의 이름, 프로필 (`/api/user-info`)을 불러오는 부분이 온보딩 과정(`/onboarding`)에서 불러와서 온보딩 완료(`/onboarding/complete`)했을 때는 캐시된 정보를 불러오기 때문에 suspense안에 넣어주는 것이 불필요하다 생각되어 따로 프로필 부분에만 suspense를 사용했습니다. 아래 스터디 리스트로 가는 버튼도 같이 suspense안으로 넣어두었습니다.

기본 유저 이미지도 추가시켜야할 것 같습니다.

### `/login`
아이디 저장버튼은 추후에 구현할 예정입니다. (아직 어떻게 구현해야 할지 모르겠습니다.)
<br>

## ⭐️ Review point
회원가입 후에 로그인을 한번 더 해야하는 로직으로 변경할 지 그대로 유지할 지 모르겠습니다.

로그인 후에 `/auth/redirect` 에서 `/api/onboarding` 으로 get요청을 보낸후 온보딩 정보가 있는 지를 판단해서 리다이렉트 하는데 이 부분이 캐시되어서 실제 온보딩을 완료했을 때 캐시된 정보가 불러와서 오류가 있었습니다. 현재는 type으로 key값을 변경해서 하고 있는데 확인하는 api를 따로 만들어야할 지 아님 현재를 유지할 지 모르겠습니다.
<br>

## 📷 Demo

`/signup`

https://github.com/user-attachments/assets/078d6566-5562-4e33-8b9d-c9a720ee5678

`/onboarding/complete`

https://github.com/user-attachments/assets/e17742bd-3020-486c-b686-1cadb0f28f03

`/login`

https://github.com/user-attachments/assets/ee715e10-3a82-4692-bbf3-ffebe5753ceb

<br>

2024-09-02 01:56 UTC, soyoung125 reviewed
제 기억으로는 ic-user.svg가 기본 유저 이미지였던 것으로 기억합니다.

2024-09-02 01:56 UTC, soyoung125 commented on src/components/OnBoarding/Profile/Profile.tsx
>    const position = POSITIONS_KR_DATA[POSITIONS_DATA.indexOf(onboardingCompleteData.data.position)];
온보딩을 건너뛰면 오류가 생깁니다.
![image](https://github.com/user-attachments/assets/d2c21350-e1d6-45a3-8343-44f91a77e1af)

2024-09-03 03:13 UTC, ejinn1 commented on src/components/OnBoarding/Profile/Profile.tsx
>    const position = POSITIONS_KR_DATA[POSITIONS_DATA.indexOf(onboardingCompleteData.data.position)];
아직 온보딩을 건너뛰는 단계를 고려하지 않았어요

2024-09-03 03:42 UTC, sikkzz requested changes

2024-09-03 03:42 UTC, sikkzz commented on src/app/signup/page.tsx
<img width="696" alt="스크린샷 2024-09-03 오후 12 27 23" src="https://github.com/user-attachments/assets/ccfe6f96-cb24-44e5-8790-5b057f723d0a">

warning 있네요 form tag 관련일꺼에요

2024-09-03 03:42 UTC, sikkzz commented on src/app/api/onboarding/route.ts
> +    return NextResponse.json({ message: "ok", status: 400, data });
이거 왜 바뀐거에요? 400이면 ok도 아니고 data도 넘어가면 안되는거 아닌가용

2024-09-03 03:42 UTC, sikkzz commented on src/components/Login/LoginBottom/LoginBottom.tsx
<img width="685" alt="스크린샷 2024-09-03 오후 12 25 43" src="https://github.com/user-attachments/assets/9054ae10-62a3-4ba4-976f-539534cfdd73">

루트 페이지에서 에러 뜨는데 이 컴포넌트 Link 태그 관련인 거 같아요

2024-09-03 03:42 UTC, sikkzz commented on src/components/OnBoarding/Profile/Profile.tsx
> +    (onboardingCompleteData.data &&
onboardingCompleteData.data && 이거 없으면 뭐 에러 나는걸까요?

2024-09-03 03:42 UTC, sikkzz commented on src/hooks/api/signup/usePostSignUpMutation.ts
> +    },
이거 쿼리 업데이트 해줄 필요 없지 않나요? 의도된게 있을까요

2024-09-03 03:42 UTC, sikkzz commented on src/hooks/login/useLoginForm.ts
> +    console.log(error);
제거해도 될 거 같아요

2024-09-03 03:42 UTC, sikkzz commented on src/hooks/login/useLoginForm.ts
> +      router.push("http://localhost:3000/auth/redirect");
/auth/redirect로 했을 때 문제점이 있을까요

2024-09-03 03:42 UTC, sikkzz commented on src/hooks/signup/useSignUpForm.ts
> +    /^(?=.*[a-zA-Z])(?=.*[!@#$%^*+=-])(?=.*[0-9]).{8,20}$/.test(signupForm.password);
정규식 두개는 regex.ts 상수 파일 하나 만들어서 사용하는게 좋을 거 같아요

2024-09-03 03:42 UTC, sikkzz commented on src/hooks/signup/useSignUpForm.ts
> +        router.push("http://localhost:3000/auth/redirect");
여기도 /auth/redirect path 상수화 해서 쓰면 될 거 같아요

2024-09-03 04:21 UTC, ejinn1 commented on src/app/api/onboarding/route.ts
> +    return NextResponse.json({ message: "ok", status: 400, data });
온보딩 여부를 확인할 때 data가 null인 지 확인하는 방식으로 해서 아래 방식으로 수정했습니다
```js
if (error) {
      return NextResponse.json({ message: "error", status: 400 });
    }

// 온보딩을 건너뛰었거나 온보딩을 했는 지의 여부 확인
if (!data) {
  return NextResponse.json({ message: "ok", status: 204, data });
}

return NextResponse.json({ message: "ok", status: 200, data });

```

2024-09-03 06:11 UTC, ejinn1 commented on src/components/Login/LoginBottom/LoginBottom.tsx
Link 태그가 루트랑 LoginBottom 컴포넌트에 겹쳐서 있어서 에러나는거라서 루트에 Link 태그의 위치를 수정했습니다.

2024-09-03 06:11 UTC, ejinn1 commented on src/components/OnBoarding/Profile/Profile.tsx
> +    (onboardingCompleteData.data &&
온보딩을 스킵했을 때 에러가 나서 스킵했을 때는 빈 문자열로 표현했어요

2024-09-03 06:12 UTC, ejinn1 commented on src/hooks/api/signup/usePostSignUpMutation.ts
> +    },
바로 수정했슴니다

2024-09-03 06:42 UTC, ejinn1 commented on src/components/OnBoarding/Profile/Profile.tsx
>    const position = POSITIONS_KR_DATA[POSITIONS_DATA.indexOf(onboardingCompleteData.data.position)];
온보딩 스킵하면 빈 문자열로 나오도록 수정했어요

2024-09-03 07:33 UTC, soyoung125 commented on src/app/login/page.tsx
> +        <LoginSocail />
*LoginSocial

2024-09-03 07:33 UTC, soyoung125 commented on src/app/signup/page.tsx
> +            />
여기도 비밀번호 볼 수 있게 수정부탁드립니다!

2024-09-04 01:21 UTC, detourguru commented on src/app/login/page.tsx
> +import LoginSocail from "@/components/Login/LoginSocial/LoginSocail";
오탈자 있는 것 같습니다 *LoginSocial

2024-09-04 01:36 UTC, jisong3377 commented on src/app/signup/page.tsx
> +                  alt="epen eye"
alt라서 문제는 없겠지만 오탈자요 open

2024-09-04 01:39 UTC, ejinn1 commented on src/app/signup/page.tsx
> +            />
수정했습니다!

2024-09-04 08:57 UTC, sikkzz requested changes

2024-09-04 08:57 UTC, sikkzz commented on src/utils/supabase/middleware.ts
> +  if ((user && request.nextUrl.pathname === "/login") || request.nextUrl.pathname === "/") {
조건부가 잘못된 거 아닐까요? user가 있어야 로그인 상태인거고 로그인 상태에서 login page나 루트 페이지 접근시 리다이렉트 동작이 맞으므로 user && (request.nextUrl.pathname === "/login" || request.nextUrl.pathname === "/") 가 맞을 거 같아요

2024-09-04 09:04 UTC, ejinn1 commented on src/utils/supabase/middleware.ts
> +  if ((user && request.nextUrl.pathname === "/login") || request.nextUrl.pathname === "/") {
바로 수정하겠습니다

2024-09-04 13:43 UTC, ejinn1 reviewed
`/auth/redirect` 페이지를 삭제하고 리다이렉션하는 기능을 middleware에 포함시켰습니다.
로그인, 회원가입을 한 후에 `/walk-through` 페이지로 보내면 middleware가 온보딩 여부를 판단한 후에 온보딩을 진행했으면 `/study-room/list`로, 아니면 `/walk-through`로 리다이렉션 되도록 설정했습니다. 
온보딩 여부는 온보딩을 진행한 후에 userinfo 테이블의 `onboardingCheck` 컬럼의 값을 true로 변경하고 이후 미들웨어에서 그 값을 조회하는 방식으로 온보딩 여부를 판단하도록 하였습니다. 
기존 `/api/onboarding` 으로 온보딩 여부 판단을 추가하기 전으로 되돌렸습니다.

브랜치 새로 파서 했어야했는데 이 브랜치에서 진행해서 변경점이 꽤 생겼습니다..

2024-09-05 03:28 UTC, sikkzz approved these changes

2024-09-05 03:34 UTC, detourguru approved these changes

2024-09-05 03:43 UTC, soyoung125 approved these changes

2024-09-05 03:44 UTC, jisong3377 approved these changes

2024-09-05 03:55 UTC, merged