79 front task create community post list page publishing
Meetie-One/Meetie-front pull request #83
Opened 2024-09-01 17:08 UTC by soyoung125

- [GITHUB ISSUE LINK]()

## 💡 변경사항 & 이슈
커뮤니티 리스트 페이지 퍼블리싱 및 기능 구현
<br>

## ✍️ 관련 설명
community-post/list 에서 확인 가능합니다.

커뮤니티 게시글 추천 카드 구현
주제별 게시글 리스트, 필터 설정 기능 구현

필터 설정의 경우 탐색하기 페이지의 스터디 찾기와 친구 찾기의 필터 컴포넌트와 같이 사용할 수 있을 것 같아서 공통컴포넌트로 제작했습니다.
![image](https://github.com/user-attachments/assets/b05b5f48-2c71-4d79-af03-3192c5a360ad)
![image](https://github.com/user-attachments/assets/8dccb0e3-6621-4798-8c09-4ce0be1238bb)
![image](https://github.com/user-attachments/assets/ff556cab-d600-4e64-85c6-053e8fab24d8)
<br>

## ⭐️ Review point
페이지 경로를 community-post/list로 하긴 했는데 community/post/list로 하는 게 나을지 그대로 가는 게 좋을지 고민되네요. 혹시 의견 있으시다면 말씀 부탁드려요.

테스트 진행해보시고 문제가 발견된다면 말씀 부탁드려요.

혹시 채연님께서 필터 컴포넌트 사용하실 의향이 있다면 적용해보시고 고쳐야 할 부분 말씀해주시면 감사하겠습니다.
<br>

## 📷 Demo
https://github.com/user-attachments/assets/42eaf941-84e1-4dd4-9a78-4d565b57de05

<br>

2024-09-03 03:35 UTC, ejinn1 approved these changes
경로는 그냥 `/community`에 해도 될거같아요

2024-09-03 04:05 UTC, sikkzz requested changes
저도 /community로 그냥 사용해도 될 거 같아요

필터는 스터디 목록이랑 같이 사용하시려면 양쪽 다 api 개발까지 마친 이후에 공통화에 문제 없을지 확인해봐야 하지 않을까요? 지금은 이론상 문제 없을 거 같긴해요

2024-09-03 04:05 UTC, sikkzz commented on src/app/community-post/list/page.tsx
> +      </div>
todo로 공통 컴포넌트 제작 주석처리 부탁드려요. 이후에 스터디 탐색 쪽 searchbar랑 공통화 시켜서 사용하면 될 거 같아요

2024-09-03 04:05 UTC, sikkzz commented on src/components/CommunityPost/List/CreatePostButton/CreatePostButton.tsx
<img width="132" alt="스크린샷 2024-09-03 오후 12 51 40" src="https://github.com/user-attachments/assets/579872a6-2697-4178-813f-3d387dc579cc">

이거 그라데이션 의도하신건지 모르겠지만 바깥쪽으로 갈수록 흰색이여서 어색하지 않나요? 저만 그런가?..

2024-09-03 04:05 UTC, sikkzz commented on src/components/common/Filter/Filter.tsx
<img width="360" alt="스크린샷 2024-09-03 오후 12 57 42" src="https://github.com/user-attachments/assets/c352cd51-3fff-4e22-bb5e-00c57b326ad6">

select list 이상한곳에 뜨는데 저만 그런걸까요?

2024-09-03 04:18 UTC, jisong3377 commented on src/components/common/Filter/Filter.tsx
저는 select 알맞은 위치에 뜹니다

2024-09-03 04:20 UTC, jisong3377 commented
<img width="398" alt="스크린샷 2024-09-03 오후 1 16 00" src="https://github.com/user-attachments/assets/5a056d91-1148-4621-880b-02e1bf2d79dc">
글씨가 잘려 보여요 !

2024-09-03 04:24 UTC, jisong3377 commented on src/app/community-post/list/page.tsx
> +      </div>
이부분 수정될 거 같은데 그래도 남겨봐욥
<img width="398" alt="스크린샷 2024-09-03 오후 1 16 00" src="https://github.com/user-attachments/assets/7b12fd9b-3aca-4e2b-883a-acc7677911f0">
저한테는 글씨가 잘려 보였습니다

2024-09-03 04:25 UTC, jisong3377 commented on src/app/community-post/list/page.tsx
> +      </div>
이부분 수정될 거 같은데 그래도 남겨봐욥
<img width="398" alt="스크린샷 2024-09-03 오후 1 16 00" src="https://github.com/user-attachments/assets/7b12fd9b-3aca-4e2b-883a-acc7677911f0">
저한테는 글씨가 잘려 보였습니다

2024-09-03 04:27 UTC, jisong3377 approved these changes

2024-09-03 06:43 UTC, soyoung125 commented on src/app/community-post/list/page.tsx
> +      </div>
![image](https://github.com/user-attachments/assets/98c7368d-9717-4c2f-a1c7-24b1471989e2)

너비 100%로 업데이트했습니다!

2024-09-03 06:47 UTC, soyoung125 commented on src/components/CommunityPost/List/CreatePostButton/CreatePostButton.tsx
피그마에 그라데이션이 있어서 적용했는데 피그마에서 보이는 것보다 더 하얗게 나오긴하네요.

그라데이션 대비 감소
![image](https://github.com/user-attachments/assets/722b7c40-378b-460c-93bb-5863945606c8)
아니면 그라데이션을 제거
![image](https://github.com/user-attachments/assets/54cb7765-adf8-483c-9b7c-12c4a1bf6b73)
어떤게 더 괜찮아 보이시나요

2024-09-03 06:47 UTC, soyoung125 commented on src/components/common/Filter/Filter.tsx
음.... 저는 저렇게 뜬 적이 없어서 모르겠네요.
테스트해보겠습니다.

2024-09-03 07:00 UTC, ejinn1 commented on src/components/CommunityPost/List/CreatePostButton/CreatePostButton.tsx
전 위에꺼가 좋아보여요

2024-09-03 07:06 UTC, soyoung125 commented on src/components/common/Filter/Filter.tsx
원인을 못 찾겠습니다..

2024-09-03 08:18 UTC, jisong3377 commented on src/components/CommunityPost/List/CreatePostButton/CreatePostButton.tsx
위에꺼용

2024-09-03 08:55 UTC, sikkzz commented on src/components/common/Filter/Filter.tsx
todo로 이후 해결만 적어주세요

2024-09-04 01:24 UTC, detourguru approved these changes

2024-09-04 08:57 UTC, sikkzz approved these changes

2024-09-04 17:15 UTC, merged