6 front task my page publishing
Meetie-One/Meetie-front pull request #9
Opened 2024-08-08 17:54 UTC by soyoung125

- [https://github.com/Meetie-One/Meetie-front/issues/6](https://github.com/Meetie-One/Meetie-front/issues/6)

## 💡 변경사항 & 이슈
마이페이지 퍼블리싱
<br>

## ✍️ 관련 설명
마이페이지 기본적인 퍼블리싱을 완료했습니다.
마이페이지와 프로필 설정 페이지, 능력 현황 페이지의 퍼블리싱을 진행했습니다.
코드의 양이 많아질 것 같아서 이미지나 아이콘 적용은 아직 미구현된 상태입니다.
피그마를 바탕으로 퍼블리싱을 진행했지만 코드 재상용과 레이아웃 적용 등의 이유로 약간의 변동을 준 부분도 존재합니다.

프로필 설정 페이지의 경우 피그마에는 존재하지 않으나 강사님이 주신 자료에 있어서 퍼블리싱을 진행했습니다.

마이페이지에서 사용되는 컬러와 폰트 설정을 추가했습니다.
<br>

## ⭐️ Review point
정상적으로 잘 동작하는지 확인 부탁드며, 디자인에 문제가 있다면 말씀해 주세요.
<br>

## 📷 Demo
### my page
![screencapture-localhost-3001-mypage-2024-08-09-02_23_18](https://github.com/user-attachments/assets/f8e35ba7-e0e6-4268-a5ea-8856661b84dc)

### profile page
![screencapture-localhost-3001-mypage-profile-2024-08-09-02_28_29](https://github.com/user-attachments/assets/25a7236e-9913-4af8-b51b-e183c313dadd)

### ability page
![screencapture-localhost-3001-mypage-ability-2024-08-09-02_33_49](https://github.com/user-attachments/assets/6196c55f-20a4-499d-84a7-1908dfbb2f52)

### badge drawer
![image](https://github.com/user-attachments/assets/0a07a3be-8333-45e4-8430-2036a0f0d0e4)

<br>

2024-08-09 01:27 UTC, jisong3377 approved these changes

2024-08-09 01:28 UTC, ejinn1 approved these changes

2024-08-09 02:17 UTC, sikkzz requested changes
퍼블리싱 단계라 신경 안쓰신거겠지만 겹치거나 반복되는 코드들은 컴포넌트화에 꼭 신경써주세요!

추가적으로 PR 작성 시 해당 레이아웃 확인할 수 있는 routing 주소 작성해주시면 리뷰에 도움이 됩니다

/mypage 에서 확인 가능합니다 이런식으로요

2024-08-09 02:17 UTC, sikkzz commented on apps/meetie-service/src/app/globals.css
> +    --info-600: #3f3fff;
네이밍을 Info로 잡으신 이유가 있을까요? 컬러값에 비슷한 쪽으로 네이밍 잡는게 더 좋을 거 같아요

--white-100
--blue-100 등 blue나 white, 보라 계열은 제가 primary로 잡아놨으니 primary쪽으로요

2024-08-09 02:17 UTC, sikkzz commented on apps/meetie-service/src/app/mypage/ability/page.tsx
> +  const [isOpen, setIsOpen] = useState(false);
코드간 공백 한줄씩 넣어주는게 어떠신가요? 저는 같은 종류의 코드끼리는 붙여놓지만 다른 종류는 공백을 꼭 넣어주는 편입니다

```jsx
   const router = useRouter()

   const [isOpen, setIsOpen] = useState();
   const [isTest, setIsTest] = useState();

   const params = useParams()
```

이런식으로 같은 종류끼리만 묶어놓는 편이에요 다들 의견 한번씩 부탁드려요

@soyoung125 @ejinn1 @detourguru @jisong3377

2024-08-09 02:17 UTC, sikkzz commented on apps/meetie-service/src/app/mypage/ability/page.tsx
> +          }}
한줄짜리여도 인라인 말고 함수로 작성하기로 컨벤션 정했던거 같은데 이런 onClick들도 다 함수로 작성하면 너무나 많아질 거 같네요 어떠신가요? 다른분들은

@soyoung125 @ejinn1 @detourguru @jisong3377 

추가적으로 한줄짜리를 인라인으로 작성할때는 중괄호 제거가 가능합니다

```jsx
onClick={() => setIsOpen(false)}
```

2024-08-09 02:17 UTC, sikkzz commented on apps/meetie-service/src/app/mypage/ability/page.tsx
> +      <div className="flex flex-row justify-between items-center h-10 pl-1.5 pr-3">
여기만 해당되는 내용은 아니긴한데 flex-row가 flexbox default 옵션이라 안써도 동일한거로 알고 있는데 아닐까요?

맞다면 flex-row 옵션은 전체적으로 삭제해도 될 거 같아요

2024-08-09 02:17 UTC, sikkzz commented on apps/meetie-service/src/app/mypage/page.tsx
> +        <div>alarm</div>
아이콘으로 변경 예정 주석으로 todo 달아주시면 좋을 거 같아요

2024-08-09 02:17 UTC, sikkzz commented on apps/meetie-service/src/app/mypage/page.tsx
> +      <div className="flex flex-row justify-between items-end mt-10 px-4">
여기 items-end말고 아래 link 컴포넌트에서 self-end 쓰는게 더 좋을거 같네요

2024-08-09 02:17 UTC, sikkzz commented on apps/meetie-service/src/app/mypage/page.tsx
> +        <Link href="mypage/profile">
여기다가 self-end 달아주시면 동일합니다

2024-08-09 02:17 UTC, sikkzz commented on apps/meetie-service/src/app/mypage/page.tsx
> +          <div className="h-2.5 border border-primary-200" />
해당 요소는 이렇게 div로 작성하기 보다는 ::after를 이용해서 많이 작성합니다. 가상 요소라고 지칭하죠 한번 서칭 해보시면 좋을 거 같아요

2024-08-09 02:17 UTC, sikkzz commented on apps/meetie-service/src/app/mypage/page.tsx
> +          </article>
버튼 아이콘, 텍스트, value props로 받아서 컴포넌트 하나로 작성하면 중복된 코드 작성을 피할 수 있을 거 같네요

2024-08-09 02:17 UTC, sikkzz commented on apps/meetie-service/src/app/mypage/page.tsx
> +            </article>
여기도 컴포넌트화 하는게 좋을 거 같네요. ability 페이지에서 사용될 거 까지 고려해서 만들면 더 좋을 거 같아요

2024-08-09 02:17 UTC, sikkzz commented on apps/meetie-service/src/app/mypage/page.tsx
> +            </li>
여기도 메뉴 아이템을 컴포넌트화 해서 사용하는게 좋을 거 같아요

앞에 아이콘 여부, 타이틀, 뒤에 아이콘 여부, 토글 여부 등 고려할 부분이 조금 있겠네요

2024-08-09 02:17 UTC, sikkzz commented on apps/meetie-service/src/app/mypage/ability/page.tsx
> +      </section>
벳지 컴포넌트화 (마이페이지랑 연동해서)

2024-08-09 02:17 UTC, sikkzz commented on apps/meetie-service/src/app/mypage/ability/page.tsx
> +        }
저는 백틱으로 작성해서 조건부를 처리하는 편이에요 큰 차이점이 존재하는건 아니지만 + 가 들어간게 조금 거슬리긴 해서 알려드려봐요

<img width="1092" alt="스크린샷 2024-08-09 오전 11 07 20" src="https://github.com/user-attachments/assets/9030a49f-efa5-45a7-a898-1cfd9cc54d30">

2024-08-09 02:17 UTC, sikkzz commented on apps/meetie-service/src/app/mypage/ability/page.tsx
> +      <main
하단 바텀시트로 열리는 부분도 컴포넌트화 하는게 좋겠네요 재사용성은 없지만 따로 구성하는게 좋을 거 같아요

2024-08-09 02:17 UTC, sikkzz commented on apps/meetie-service/src/app/mypage/profile/page.tsx
> +  return (
상단 비즈니스 로직 코드와 리턴문 사이도 공백 하나만 부탁드려요!

명확한 구분을 주기 위해서 입니다

2024-08-09 02:17 UTC, sikkzz commented on apps/meetie-service/src/app/mypage/profile/page.tsx
> +            </div>
컴포넌트화

2024-08-09 02:17 UTC, sikkzz commented on apps/meetie-service/src/app/mypage/profile/page.tsx
> +            </div>
컴포넌트화

2024-08-09 02:17 UTC, sikkzz commented on apps/meetie-service/src/app/mypage/profile/page.tsx
> +          <div className="px-4 flex flex-nowrap gap-4 overflow-x-scroll">
스크롤바 지우는게 더 자연스러울 거 같아요

2024-08-09 02:17 UTC, sikkzz commented on apps/meetie-service/src/app/mypage/profile/page.tsx
> +          <div className="px-4 flex flex-nowrap gap-4 overflow-x-scroll">
여기도 스크롤바 없어야 겠네요

2024-08-09 02:17 UTC, sikkzz commented on apps/meetie-service/src/app/mypage/profile/page.tsx
> +        </div>
컴포넌트화

2024-08-09 02:17 UTC, sikkzz commented on apps/meetie-service/src/app/mypage/profile/page.tsx
> +          </article>
컴포넌트화

2024-08-09 02:20 UTC, sikkzz commented
추가적으로 커밋 히스토리를 확인해보니까 히스토리도 많이 꼬이고 커밋 메시지 양식 안맞는부분도 있네요

다음부터는 신경써서 작업 부탁드려요 모르시거나 어려운게 있다면 물어보면 알려드리도록 하겠습니다~

2024-08-09 04:26 UTC, soyoung125 commented on apps/meetie-service/src/app/globals.css
> +    --info-600: #3f3fff;
보통 디자인 시스템에서 info 가 파란색 계열이라서 일단 info로 잡았는데 blue로 하는 게 더 직관적인 것 같긴 하네요. 보라색 계열은 옮겨놓겠습니다.

2024-08-09 04:27 UTC, soyoung125 commented on apps/meetie-service/src/app/mypage/ability/page.tsx
> +  const [isOpen, setIsOpen] = useState(false);
나중에 코드가 많아질 경우를 생각하면 이 방법이 더 좋을 것 같네요

2024-08-09 04:40 UTC, soyoung125 commented on apps/meetie-service/src/app/mypage/ability/page.tsx
> +          }}
컨벤션으로 지정했던걸 놓쳤었네요,, 
저는 한줄짜리 코드 인라인으로 작성하는 것도 좋은데 저번에 함수로 빼서 작성하는 게 더 읽기 편하다고 하셨어서 함수로 작성하는 게 더 좋을 것 같습니다.

2024-08-09 04:43 UTC, soyoung125 commented on apps/meetie-service/src/app/mypage/ability/page.tsx
> +      <div className="flex flex-row justify-between items-center h-10 pl-1.5 pr-3">
확인해보니까 그렇네요. flex-row 삭제하겠습니다.

2024-08-09 05:07 UTC, soyoung125 commented on apps/meetie-service/src/app/globals.css
> +    --info-600: #3f3fff;
수정 완료했습니다.
![image](https://github.com/user-attachments/assets/e094c5ce-ee63-40eb-b6d6-47eeef8b6364)

2024-08-09 05:13 UTC, soyoung125 commented on apps/meetie-service/src/app/mypage/ability/page.tsx
> +          }}
해결했습니다.
```
 const handleClick = () => setIsOpen(true);
```

```
 onClick={handleClick}
```

2024-08-09 05:13 UTC, soyoung125 commented on apps/meetie-service/src/app/mypage/ability/page.tsx
> +  const [isOpen, setIsOpen] = useState(false);
수정했습니다.

2024-08-09 05:17 UTC, soyoung125 commented on apps/meetie-service/src/app/mypage/ability/page.tsx
> +      <div className="flex flex-row justify-between items-center h-10 pl-1.5 pr-3">
수정했습니다.

2024-08-09 05:29 UTC, soyoung125 commented on apps/meetie-service/src/app/mypage/page.tsx
> +      <div className="flex flex-row justify-between items-end mt-10 px-4">
수정했습니다. flex안에 아이템이 여러 개 있을 때는 self를 쓰는게 더 낫겠네요

2024-08-09 06:09 UTC, soyoung125 commented on apps/meetie-service/src/app/mypage/page.tsx
> +          <div className="h-2.5 border border-primary-200" />
이 부분 같은 경우에는 해당 div가 아래의 내 정보 박스에서도 동일하게 사용할 수 있을 것 같아서 div로 작성했던 것입니다. 그래서 컴포넌트로 분리한 후 재사용하려고 했는데 after를 활용하는 방식이 나을까요??

2024-08-09 06:48 UTC, sikkzz commented on apps/meetie-service/src/app/mypage/page.tsx
> +          <div className="h-2.5 border border-primary-200" />
아 아래도 사용되는군요 컴포넌트 분리 해보시고 그대로 활용 가능하면 변경 없이 사용하셔도 괜찮을 거 같아요!

2024-08-12 08:49 UTC, soyoung125 commented on apps/meetie-service/src/app/mypage/page.tsx
> +        <div>alarm</div>
이미지 처리 관련 코드 TODO 주석 추가 완료했습니다.

2024-08-12 08:49 UTC, soyoung125 commented on apps/meetie-service/src/app/mypage/page.tsx
> +          <div className="h-2.5 border border-primary-200" />
여기 컴포넌트 분리하려다가 아랫부분 디자인이 약간의 수정이 있어서 그냥 after로 디자인 구현했습니다!

2024-08-12 08:50 UTC, soyoung125 commented on apps/meetie-service/src/app/mypage/page.tsx
> +          </article>
컴포넌트 분리 완료했습니다.

2024-08-12 08:51 UTC, soyoung125 commented on apps/meetie-service/src/app/mypage/page.tsx
> +            </article>
컴포넌트 분리 완료했습니다. ability 페이지까지 고려해서 컴포넌트 생성했는데 ability 페이지와 디자인이 다른 점이 있어서 재활용은 못했습니다. 아마 뱃지 아이콘을 추가한 이후에 더 세분화해서 재사용할 수 있을 것 같습니다.

2024-08-12 08:52 UTC, soyoung125 commented on apps/meetie-service/src/app/mypage/page.tsx
> +            </li>
컴포넌트 분리 완료했습니다.

2024-08-12 08:52 UTC, soyoung125 commented on apps/meetie-service/src/app/mypage/ability/page.tsx
> +      </section>
컴포넌트 분리 완료했습니다.

2024-08-12 08:53 UTC, soyoung125 commented on apps/meetie-service/src/app/mypage/ability/page.tsx
> +        }
디자인 조건부 처리하는 코드에서 모두 백틱 사용하도록 수정 완료했습니다.

2024-08-12 08:53 UTC, soyoung125 commented on apps/meetie-service/src/app/mypage/ability/page.tsx
> +      <main
하단 바텀시트 컴포넌트 분리 완료했습니다.

2024-08-12 08:53 UTC, soyoung125 commented on apps/meetie-service/src/app/mypage/profile/page.tsx
> +  return (
공백 추가했습니다.

2024-08-12 08:54 UTC, soyoung125 commented on apps/meetie-service/src/app/mypage/profile/page.tsx
> +            </div>
컴포넌트 분리 완료했습니다.

2024-08-12 08:54 UTC, soyoung125 commented on apps/meetie-service/src/app/mypage/profile/page.tsx
> +            </div>
컴포넌트 분리 완료했습니다.

2024-08-12 08:54 UTC, soyoung125 commented on apps/meetie-service/src/app/mypage/profile/page.tsx
> +          <div className="px-4 flex flex-nowrap gap-4 overflow-x-scroll">
스크롤바 숨길 수 있도록 global.css에 관련 css 코드 추가해서 적용했습니다.

2024-08-12 08:55 UTC, soyoung125 commented on apps/meetie-service/src/app/mypage/profile/page.tsx
> +          <div className="px-4 flex flex-nowrap gap-4 overflow-x-scroll">
여기도 스크롤바 제거했습니다.

2024-08-12 08:55 UTC, soyoung125 commented on apps/meetie-service/src/app/mypage/profile/page.tsx
> +        </div>
컴포넌트 작업 완료했습니다.

2024-08-12 08:55 UTC, soyoung125 commented on apps/meetie-service/src/app/mypage/profile/page.tsx
> +          </article>
컴포넌트 분리 완료했습니다

2024-08-13 01:00 UTC, detourguru approved these changes

2024-08-13 02:14 UTC, sikkzz requested changes

2024-08-13 02:14 UTC, sikkzz commented on apps/meetie-service/src/app/mypage/ability/page.tsx
> +export type TSelectedBadge = { type: string; badge: BadgeType };
해당 파일에서는 미사용되는 코드 같은데 맞을까요?

2024-08-13 02:14 UTC, sikkzz commented on apps/meetie-service/src/app/mypage/ability/page.tsx
> +export type TSelectedBadge = { type: string; badge: BadgeType };
이 코드 사용하시는거라면 interface로 변경 부탁드려요

2024-08-13 02:14 UTC, sikkzz commented on apps/meetie-service/src/app/mypage/ability/page.tsx
> +import { BADGESE } from "@/constants/badges";
오타인걸까요? 아니면 네이밍 의도가 궁금합니다 BADGES일거 같은데

추가적으로 저는 데이터 상수임을 인지할 수 있게 BADGE_DATA 이렇게 사용하는 편인데 한번 고려해보시면 좋을 거 같아요!

2024-08-13 02:14 UTC, sikkzz commented on apps/meetie-service/src/app/mypage/page.tsx
> +        <Link href="mypage/profile" className="self-end">
링크도 상수화해서 사용하는게 좋을 거 같아요

재사용성 고려 + 누락이나 실수 대비용으로 좋습니다. 이건 다음 회의때 제가 팀원들한테 공유 드릴게요 사용하던 예시 이미지 달아드려요

<img width="906" alt="스크린샷 2024-08-13 오전 10 54 10" src="https://github.com/user-attachments/assets/4209f06b-cac7-4956-a591-e2a9eefb23ac">

2024-08-13 02:14 UTC, sikkzz commented on apps/meetie-service/src/app/mypage/page.tsx
> +          <InformationCard count={13} icon={<div className="h-10">icon</div>} type="스터디 친구" />
type이라는 props 네이밍 보다는 text or title이 더 낫지 않을까요?

2024-08-13 02:14 UTC, sikkzz commented on apps/meetie-service/src/app/mypage/page.tsx
> +            <BadgeCard type="피드백" level={2} showLevel />
이후 추가적인 확장성이 없어진다면 showLevel props는 지우고 사용하면 될 거 같습니다. 아마 여지가 남아있어서 남겨놓은거라 생각하는데 맞겠죠?

2024-08-13 02:14 UTC, sikkzz commented on apps/meetie-service/src/components/mypage/Header.tsx
> +    <>
Fragment는 최상위 태그가 있다면 불필요한 코드일 거 같아요. 전체적으로 돌면서 최상위 태그가 존재한다면 다 지워주세요 리뷰하면서 꽤 많이 확인한거 같아요

2024-08-13 02:14 UTC, sikkzz commented on apps/meetie-service/src/components/mypage/MenuListItem.tsx
> +};
이렇게 작성하는거보다 isToggle props 하나 더 받아서 toggle 유무 관리하고, navigateTo가 있을때만 routing 작동할 수 있게 작성하는게 코드 간소화에 도움 될 거 같아요

2024-08-13 02:14 UTC, sikkzz commented on apps/meetie-service/src/components/mypage/MenuListItem.tsx
> +};
추가적으로 navigateTo props의 데이터들도 위에서 언급한대로 상수화해서 관리하면 될 거 같네요

2024-08-13 02:14 UTC, sikkzz commented on apps/meetie-service/src/components/mypage/dividers/Divider.tsx
```jsx
const Divider = () => <div className="border border-primary-100" />;

export default Divider;
```

간소화 가능합니다 ThickDivder도 마찬가지로요!

2024-08-13 02:40 UTC, soyoung125 commented on apps/meetie-service/src/app/mypage/ability/page.tsx
> +export type TSelectedBadge = { type: string; badge: BadgeType };
넵 미사용 코드맞습니다. 삭제 완료했습니다.

2024-08-13 02:53 UTC, soyoung125 commented on apps/meetie-service/src/app/mypage/ability/page.tsx
> +import { BADGESE } from "@/constants/badges";
오타를 확인 못했었네요.. 상수는 DATA를 붙이는 방식으로 해보겠습니다.

2024-08-13 04:27 UTC, soyoung125 commented on apps/meetie-service/src/app/mypage/page.tsx
> +            <BadgeCard type="피드백" level={2} showLevel />
재사용하려고 남겨놨었는데 사용하지 않을 확률이 높아서 지우겠습니다.

2024-08-13 08:15 UTC, sikkzz approved these changes

2024-08-14 01:50 UTC, merged