84 front task feat community db connection
Meetie-One/Meetie-front pull request #90
Opened 2024-09-03 09:54 UTC by soyoung125

- https://github.com/Meetie-One/Meetie-front/issues/84

## 💡 변경사항 & 이슈
커뮤니티 게시글 생성, 조회 DB 연동
<br>

## ✍️ 관련 설명
게시글 생성 -> community/create 에서 확인 가능합니다.

게시글 조회 -> community 에서 확인 가능합니다.

추천 게시글은 랜덤으로 데이터를 불러오는 것으로 처리했습니다.

게시글 필터링
`검색`, `태그`, `정렬순서`, `게시일` 을 사용해서 데이터 필터링을 진행하고 있습니다.
<br>

## ⭐️ Review point
테스트 진행해 보시고 개선해야할 부분이 있다면 말씀해주세요.
<br>

## 📷 Demo
- `community/create` -> 게시글 등록

https://github.com/user-attachments/assets/0b91648f-efd3-4ddc-98fd-71ecaea1f0ab

- `community` -> 추천 게시글

https://github.com/user-attachments/assets/ac214f7d-0867-4249-8378-a9754f44b8b9

- `community` -> 게시글 필터링
<details>
<summary>게시글 필터링 결과 이미지 보기</summary>

![image](https://github.com/user-attachments/assets/5c1a3f20-00e2-41ec-9f2d-fca622a77598)
![image](https://github.com/user-attachments/assets/f7c9e3ee-1054-4376-933c-da305f8ce298)
![image](https://github.com/user-attachments/assets/6f8f7c66-4965-4f5b-bf74-2f9274b77731)
![image](https://github.com/user-attachments/assets/21c0a977-e3f0-4f27-b906-c8d5e0d41af1)

</details>
<br>

2024-09-04 08:49 UTC, ejinn1 commented on src/app/community/page.tsx
> +      <CreatePostButton />
CreatePostButton에 `cursor-pointer` 있으면 좋을거같아요

2024-09-05 03:55 UTC, jisong3377 approved these changes

2024-09-05 05:31 UTC, sikkzz requested changes

2024-09-05 05:31 UTC, sikkzz commented on src/app/api/community/route.ts
> +      postDate: new Date(),
필요한 데이터가 생성된 시간이라면 date 필드 이럴 필요 없이 db에 createdAt 필드 하나 만들어두고 default value now로 해두면 자동으로 들어가는데 이게 낫지 않을까요? 

저도 study에서 해당 방식으로 사용하고 있거든요

<img width="673" alt="스크린샷 2024-09-05 오후 12 51 50" src="https://github.com/user-attachments/assets/fecc03fc-ca36-41d9-830c-cf0e51283494">

2024-09-05 05:31 UTC, sikkzz commented on src/apis/community/getCommunityList.ts
api 구조를 이렇게 잡는건 어떨까요? 저도 중구난방이긴해서 맞추는게 좋을 거 같은데 이전에 한번 논의 잠깐 드렸는데 

1. api 코드와 query 코드를 확인할때 파일 이동이 한번 생기는 불편함 해소
2. 각 api 마다 필요한 코드와 query, mutation만 hook파일에 모아서 사용

이러한 장점들을 살려보려고 하는데 어떤지 말씀해주세요!


```jsx
// getCommunityList.ts 삭제
// useCommunityListQuery.ts
import { type UseSuspenseQueryOptions, useSuspenseQuery } from "@tanstack/react-query";

import { GET, createInit } from "@/apis/httpMethod";

import { END_POINTS } from "@/constants/api";
import { INITIAL_FILTER_OPTION_DATA } from "@/constants/community";
import { QUERY_KEYS } from "@/constants/queryKey";

import type { FilterSelectedType, GetCommunityListResponseType } from "@/types/community";

const getCommunityList = async (filterOption?: FilterSelectedType) => {
  const options = filterOption ?? INITIAL_FILTER_OPTION_DATA;

  const data = await GET<GetCommunityListResponseType>(
    END_POINTS.COMMUNITY_LIST(options.search, options.tags, options.sort, options.date),
    createInit(),
  );

  return data;
};

export const communityListQueryOptions = (
  filterOption?: FilterSelectedType,
): UseSuspenseQueryOptions<GetCommunityListResponseType> => ({
  queryKey: [QUERY_KEYS.COMMUNITY_LIST],
  queryFn: async () => await getCommunityList(filterOption),
});

export const useCommunityListQuery = (filterOption: FilterSelectedType) => {
  return useSuspenseQuery(communityListQueryOptions(filterOption));
};

```

```jsx
// useRecommendCommunityListQuery.ts
import { type UseSuspenseQueryOptions, useSuspenseQuery } from "@tanstack/react-query";

import { GET, createInit } from "@/apis/httpMethod";

import { END_POINTS } from "@/constants/api";
import { QUERY_KEYS } from "@/constants/queryKey";

import type { GetCommunityListResponseType } from "@/types/community";

const getRecommendCommunityList = async () => {
  const data = await GET<GetCommunityListResponseType>(
    END_POINTS.COMMUNITY_LIST_RECOMMEND,
    createInit(),
  );

  return data;
};

export const randomCommunityListQueryOptions =
  (): UseSuspenseQueryOptions<GetCommunityListResponseType> => ({
    queryKey: [QUERY_KEYS.COMMUNITY_LIST_RECOMMEND],
    queryFn: async () => await getRecommendCommunityList(),
  });

export const useRandomCommunityListQuery = () => {
  return useSuspenseQuery(randomCommunityListQueryOptions());
};

```
각 api들은 hook 하나에 1개씩만 사용하려고 나눈거고 이러면 getCommunityList.ts 삭제와 더불어 나머지 api들도 삭제가 가능할 거 같아서요. 한번 보시고 의견 부탁드려요

2024-09-05 05:31 UTC, sikkzz commented on src/hooks/community/useCommunityFilter.ts
> +  }, [filterOption]);
이거 filterOption이 바뀔때마다 데이터를 업데이트 시켜주기 위한게 맞다면 useSuspenseQuery에서 refetch를 제공하는데 그걸 사용하시면 될 거 같아요

```jsx
const { data: communityListData, refetch } = useCommunityListQuery(filterOption);

useEffect(() => {
  refetch();
}, [filterOption]
```

혹시 해보시고 작동 이상하면 말씀해주세요!

2024-09-06 01:38 UTC, sikkzz requested changes

2024-09-06 01:38 UTC, sikkzz commented on src/hooks/community/useCommunityFilter.ts
> +  }, [filterOption]);
setTimeOut이 여전히 필요한건 어떤걸 의도하시는 건지 알 수 있을까요?

2024-09-06 01:43 UTC, soyoung125 commented on src/hooks/community/useCommunityFilter.ts
> +  }, [filterOption]);
timeout을 사용하지 않으면 api 요청이 너무 많아져서 적용했습니다.
강의를 들을 때도 강사님이 검색 관련해서 해당 코드를 사용하셨어서 적용했습니다.

2024-09-06 09:27 UTC, detourguru approved these changes

2024-09-07 03:07 UTC, ejinn1 approved these changes

2024-09-09 03:36 UTC, sikkzz requested changes
<img width="378" alt="스크린샷 2024-09-09 오후 12 36 06" src="https://github.com/user-attachments/assets/1e3eb191-607f-4b99-b98c-fbc16f154a63">

이거 사이즈 한번 고치셨던거 같은데 또 이러네요? 확인 부탁드려요

2024-09-09 03:40 UTC, sikkzz requested changes

2024-09-09 03:40 UTC, sikkzz commented on src/components/CommunityPost/List/SearchSheet/SearchSheet.tsx
의도는 이해가 가지만 사실 searchbar 클릭 시 sheet가 열리는 접근이 한번 더 들어가는게 사용성이 떨어지는 요소가 될 수 있어 보여요

최근 검색어 저장 공간 떄문이라면 네이버 처럼 하단으로 열리게 만들어 놓는게 더 좋긴 할텐데 우선은 넘어갈게요. 이후에 바꾸는걸 전 권장을 드려요

2024-09-09 03:41 UTC, sikkzz commented
> <img alt="스크린샷 2024-09-09 오후 12 36 06" width="378" src="https://private-user-images.githubusercontent.com/100590110/365504306-1e3eb191-607f-4b99-b98c-fbc16f154a63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NTM1NDksIm5iZiI6MTcyNTg1MzI0OSwicGF0aCI6Ii8xMDA1OTAxMTAvMzY1NTA0MzA2LTFlM2ViMTkxLTYwN2YtNGI5OS1iOThjLWZiYzE2ZjE1NGE2My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQwMzQwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYWJjNTM4OTY2ZjRjZDVhN2ZjNDg4M2E2ODhjNDI0YzQyOTQ4NGZlODM5M2YyYjU2OTlhODNlNGMxNGIwNThjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ewGoed0p3s4vbEEqAJ63w1eZmf2U48K958-igqgSCms">
> 이거 사이즈 한번 고치셨던거 같은데 또 이러네요? 확인 부탁드려요

2024-09-09 04:24 UTC, soyoung125 commented on src/components/CommunityPost/List/SearchSheet/SearchSheet.tsx
input 너비 수정했습니다.

2024-09-09 08:39 UTC, sikkzz approved these changes

2024-09-09 08:41 UTC, merged