85 front task studyroom list page feat 2
Meetie-One/Meetie-front pull request #94
Opened 2024-09-05 00:58 UTC by detourguru

- [GITHUB ISSUE LINK]()

## 💡 변경사항 & 이슈
- 스터디 조회 수 update
- 북마크 기능 구현
<br>

## ✍️ 관련 설명
- 스터디 클릭 시 조회수 update 되도록 수정되었습니다
- 북마크 클릭 시 북마크 toggle 되도록 수정되었습니다
<br>

## ⭐️ Review point
#71  와 변경점이 겹치는 부분이 많아 rebase 받았습니다. 해당 브랜치 선병합 이후 현 브랜치 병합이 필요합니다
<br>

## 📷 Demo

<br>

2024-09-07 09:47 UTC, sikkzz requested changes

2024-09-07 09:47 UTC, sikkzz commented on src/components/Study/StudyList/StudyList.tsx
> +  }, [checked, userId]);
유저 정보 가져오는 api 개발된거 있습니다 그거 사용해주세요

2024-09-07 09:47 UTC, sikkzz commented on src/components/Study/Bookmark/Bookmark.tsx
북마크 테이블이 현재 상태처럼 관리할게 아니라 user가 북마크한 스터디 리스트 배열로 관리하는게 맞는거 같아요

지금 사진 테이블처럼 관리하면 다 따로 관리하게 되는데 이후에 유저가 북마크한 스터디만 모아보기 기능도 고려했을 때 테이블을 다 조회하면서 찾을 필요 없이 유저 id 찾아서 해당 유저가 북마크한 스터디 가져오는 방식으로 개발이 맞아 보이네요

그리고 지금 북마크 해도 db에서 데이터를 가져오는게 아니라 state 관리다 보니 새로고침하면 초기화 됩니다. 북마크를 한번 누른 순간부터는 취소까지는 어느 순간이든 유저한테는 북마크된 상태로 보여야 해요

<img width="1303" alt="스크린샷 2024-09-07 오후 6 43 18" src="https://github.com/user-attachments/assets/ead7d7ca-fbe2-4e69-bd0c-f6e30c0c98ee">

2024-09-07 09:47 UTC, sikkzz commented on src/components/Study/Bookmark/Bookmark.tsx
> +  };
여기 로직도 수정이 필요하겠네요. 우선 state로 관리할 필요 없습니다. 북마크 api가 성공하면 db에 업데이트 하고 해당 정보 쿼리 업데이트 후 가져와서 UI로 보여주면 됩니다.

또한 성공했을때만 해당 로직이 이루어져야 하고 실패하면 북마크 토글은 변동이 있으면 안됩니다

2024-09-09 01:21 UTC, soyoung125 approved these changes

2024-09-09 03:43 UTC, jisong3377 commented
/study-room/list에서 북마크를 체크하면 조회수가 같이 올라가요 !

2024-09-09 03:45 UTC, sikkzz commented
> /study-room/list에서 북마크를 체크하면 조회수가 같이 올라가요 !

이벤트 버블링 안막으셔서 그래요

2024-09-09 03:54 UTC, detourguru commented on src/components/Study/StudyList/StudyList.tsx
> +  }, [checked, userId]);
사용자 id만 필요한건데 그때마다 api 호출하는게 불필요할 것 같아서 auth에서 가져오도록 했습니다

검색해보니 동적으로 변동되는 데이터는 api 호출을 통해 가져오는게 좋고, 정적인 데이터라면 auth로 가져오는게 효율적이라고 하는데 어떻게 생각하시나요?

2024-09-09 03:58 UTC, soyoung125 commented on src/components/Study/Bookmark/Bookmark.tsx
> +    e.preventDefault();
e.stopPropagation()을 사용하는 것이 맞을 것 같습니다.

2024-09-09 04:16 UTC, detourguru commented on src/components/Study/Bookmark/Bookmark.tsx
저는 개인적으로 배열 형식의 데이터를 db에 저장하는걸 그렇게 선호하진 않아서 이렇게 작업하긴 했습니당

일단 별도의 테이블로 레코드를 관리하면 cascade를 걸어놔서 삭제된 study 관리를 따로 할 필요가 없는데 만약 배열로 저장하게 되면 북마크된 게시글 중 삭제된 건의 데이터의 관리가 어렵게 되기도 하는 등 원자성이 보장이 안되어서 별로인 것 같아여 어떻게 생각하시나용?

새로고침하면 초기화되는건 기능적으로 이상한 것 같긴하네요 애초에 새로고침 하면 그때 새로 select를 해와서 db에 저장된 결과를 가져와야하거든요 이건 따로 확인해보겠습니다~!

2024-09-09 04:19 UTC, sikkzz requested changes

2024-09-09 04:19 UTC, sikkzz commented on src/components/Study/StudyList/StudyList.tsx
> +  }, [checked, userId]);
react-query 특성상 데이터가 바뀌지 않는 api에 한해서는 캐싱되서 호출하기 때문에 한번 사용된 이후에는 쭉 캐싱된 상태로 사용됩니다. 그렇다면 첫 접근 이후에는 로그아웃해서 다른 계정으로 사용하기 이전까지 캐싱된 api로 사용됩니다. 게다가 이쪽 파트가 아닌 다른 파트에서 이미 한번 사용된 상태라면 더 이점이 존재하게 됩니다

그렇다면 오히려 현재 코드가 성능적으로 더 안좋은 코드 아닌가요? checked state가 변화할때 마다 supabase에 접근해서 계속 데이터를 가져오는건데 체크 할때마다 계속 사용될 거 같아서요.

2024-09-09 04:22 UTC, detourguru commented on src/components/Study/StudyList/StudyList.tsx
> +  }, [checked, userId]);
오~ 그렇군요 캐싱이 된다는 부분을 생각 못했어용 api로 사용자정보 가져오게 수정하겠습니다

2024-09-09 04:34 UTC, ejinn1 commented on public/svg/ic-bookmark-after.svg
북마크 색이 피그마에선 보라색인걸로 알고있습니당

2024-09-09 04:39 UTC, sikkzz commented on src/components/Study/Bookmark/Bookmark.tsx
혹시 배열 형식의 데이터를 db에 저장하는걸 선호하지 않는 이유가 있는걸까요? (별도 궁금증입니다)

보통의 백엔드분들이 로직 처리를 어떻게 하시는지는 몰라도 제 견해로는 유저가 북마크한 스터디 리스트를 배열로 관리하고 거기서 가져오는게 이득이지 않을까 싶거든요. 데이터가 1000개 10000개 늘어난다 쳤을때 테이블의 모든 DB를 훓으면서 하나씩 가져와야하는게 성능적으로 손해라 보였어요. DB 용량이나 데이터 갯수상으로도 제가 얘기한 방법이 이득이지 않을까요

말씀하신 삭제 데이터 관리는 로직이 하나 추가되긴 하겠지만 그또한 유저 id 찾고 거기서 해당 스터디 id를 찾아서 지워주는 로직하나만 추가되는거라 생각했어요

2024-09-09 05:02 UTC, detourguru commented on src/components/Study/Bookmark/Bookmark.tsx
움 일단 보통 대부분의 관계형 db는 각 컬럼에 단일 값만 저장되는걸 권장하고 그걸 기반으로 설계되어있어요 그래서 배열을 직접 저장하는걸 권장하지 않고, 잘 사용하지 않는 패턴입니다 (필요시 json으로 저장하거나 select할 수 있지만 select해올때 쿼리 복잡도가 높아져서 선호하지는 않습니다)

말씀하신대로 배열을 바로 저장하는 방식이 훨씬 구현도 쉽고 단순해보이지만, 실제로는 데이터가 많아질 수록 배열에서 꺼내오는 것보다 db에서 조회하는게 훨씬 빠릅니다! 왜냐면 db 자체에서 인덱싱이나 캐싱 등 제공하는 기능을 사용할 수 있거등요. 예를들어 자주 조회되는 컬럼에 인덱스를 부여하면 해당 레코드에 주소가 생겨서 걔를 바로 찾아갈 수 있다고 이해하시면 됩니다.

근데 배열을 사용하게 되면 해당 user의 정보는 빨리 찾아오더라도 결론적으로 저희가 조회해서 사용하고자 하는 배열 내 데이터를 특정해서 가져오는게 오히려 조회에 있어서는 더 복잡도가 높은 작업이 됩니다... 말이 좀 길어졌는데 백엔드 로직상으로는 이렇습니다 ㅋㅋㅋ

비슷한 논리로 추가적인 로직을 통해 삭제된 게시글을 관리하는 것보다 db에서 관리하는게 효율적이고, 데이터 무결성을 깨지 않는 방법이기도 하고요!

그래서 테이블 설계시에는 이렇게 레코드 단위로 관리하는것이 일반적으로 권장되는 방식이고, 조회해와서 사용하기에도 가장 복잡도가 높지 않은 방법이 된다고 이해하시면 좋을 것 같습니닷

2024-09-09 15:54 UTC, detourguru commented on src/components/Study/Bookmark/Bookmark.tsx
북마크 클릭 시 스키마 변경이 있어서 400 에러 나는거 확인하고 수정했습니다

2024-09-10 03:25 UTC, sikkzz commented on src/components/Study/Bookmark/Bookmark.tsx
> +  };
이거 수정 안된거 같네요 아직

2024-09-10 05:45 UTC, ejinn1 approved these changes

2024-09-10 08:59 UTC, jisong3377 approved these changes

2024-09-11 05:27 UTC, merged