95 front task delete in password find
Meetie-One/Meetie-front pull request #96
Opened 2024-09-05 09:34 UTC by ejinn1

- https://github.com/Meetie-One/Meetie-front/issues/95

## 💡 변경사항 & 이슈
첫 페이지 변경, 아이디 저장, 아이디 / 비밀번호 찾기 삭제, 스타일 수정
<br>

## ✍️ 관련 설명
`/`에서 회원가입, 소셜로그인 부분 삭제했습니다.
아이디 / 비밀번호 찾기 버튼 삭제했습니다.

아이디 저장 기능 구현했습니다
아이디 저장 버튼을 누르고 이메일 로그인을 진행하면 로컬 스토리지에 email이 저장되는 방식으로 구현하였습니다.

루트 페이지, 워크쓰루 페이지에 배경색을 추가했습니다.

온보딩 단계에서 Progress Bar 추가시켰습니다.
온보딩을 진행할 때 버튼 클릭에 transition 효과를 주었습니다

온보딩 타이틀 컴포넌트 리펙토링 했습니다.
<br>

## ⭐️ Review point
Progress Bar가 처음부터 full로 되어있을 때가 있었는데 이유가 무엇인지 모르겠습니다.
<br>

## 📷 Demo
### `/login`
<img width="1792" alt="image" src="https://github.com/user-attachments/assets/e4680a1e-c99f-49c2-a981-6dce76fa56d4">

### `/walk-through`
<img width="370" alt="image" src="https://github.com/user-attachments/assets/ade8d49d-3796-481f-b3b9-aae0b3e05fd5">

### `/onboarding`

https://github.com/user-attachments/assets/09b07e8a-08f6-405d-b20e-cf4e1aafaffd

<br>

2024-09-07 09:03 UTC, sikkzz requested changes
기능은 정상 동작 하는데 아이디가 로컬 스토리지에 저장되어 있으면 아이디 저장 체크 박스도 항상 체크 상태로 존재해야 할 거 같아요 그거만 수정 부탁드려요

<img width="341" alt="스크린샷 2024-09-07 오후 6 03 24" src="https://github.com/user-attachments/assets/ff04c28d-a282-4b07-8374-bf41d498c191">

2024-09-09 01:26 UTC, soyoung125 approved these changes

2024-09-09 03:34 UTC, sikkzz approved these changes

2024-09-09 03:47 UTC, jisong3377 approved these changes

2024-09-09 03:50 UTC, detourguru approved these changes

2024-09-09 04:52 UTC, merged